### PR TITLE
gsc: an explicitly-implemented interface member is not an ordinary-call candidate, and an explicit type argument is erased like the arguments (#4013, #4016)

### LINKED ISSUE #4013: gsc: an explicitly-implemented non-generic interface member is a candidate for an ordinary call — 'List[int32]().Add("x")' compiles and throws
Found while fixing #3998; unrelated to arrays. Filed separately because it is a general overload-resolution hole on any imported generic that also implements a non-generic interface.

## Measured on `main` (@ `b6d2f60e`)

```gsharp
package P
import System.Collections.Generic

func main2() {
    var ys = List[int32]()
    ys.Add("x")
}

main2()
```

```
Success.
```

and at run time:

```
Unhandled exception. System.ArgumentException: The value "x" is not of type "System.Int32"
and cannot be used in this generic collection. (Parameter 'value')
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at P.<Program>.<Main>$(String[] args)
```

## Why

`List<T>` implements the non-generic `System.Collections.IList`, whose `Add(object)`
accepts anything. When the argument does not match the generic `Add(T)`, overload
resolution falls through to that interface member instead of reporting `GS0154`. The stack
trace names `List<T>.System.Collections.IList.Add`, so the call really is bound to the
explicit interface implementation.

C# rejects the same program at compile time (`CS1503`): the explicit interface
implementation is not a member of `List<T>`'s public surface and is not a candidate for
`ys.Add(…)`.

## Why it matters

This is the unsound direction: a static type error becomes a run-time
`ArgumentException`. It is not specific to `List` — any imported generic exposing a
non-generic sibling of a generic member has the same hole, and it silently widens every
such call site to `object`.

## Expected

`ys.Add("x")` reports `GS0154` naming `int32` and `string`. An explicitly-implemented
interface member should not be a candidate for an ordinary member call on the implementing
type; reaching it should require an interface-typed receiver
(`cast[IList](ys).Add("x")`).

## Notes

- Independent of #3998 / #4012, but it is why #4012's `List[[3]int32].Add([4]int32{…})`
  row is not on its own proof of a member-projection gap — the `Stack[[3]int32].Push(…)`
  row is used there instead, because `Stack[T].Push(T)` has no non-generic sibling.

### LINKED ISSUE #4016: gsc: a `map[K, Derived]` does not reach an inferred `Dictionary<K, V>` slot the `List` spelling reaches
Found while writing tests for #4006. Pre-existing on `main` (`b6d2f60e`), and NOT introduced by the #4006/#4000 PR — measured identical on both sides of it.

## Repro (measured on `main`)

C# library (`<Nullable>enable</Nullable>`):

```csharp
using System.Collections.Generic;

namespace HelperLib;

public class ImportedBase { }

public static class Probes
{
    public static string CountAny<T>(List<T> items) => "any:" + items.Count;

    public static string CountAnyMap<K, V>(Dictionary<K, V> entries)
        where K : notnull
        => "anymap:" + entries.Count;
}
```

```gs
package P
import System
import System.Collections.Generic
import HelperLib

class Derived : ImportedBase {
}

// binds, verifies, runs — prints `any:1`
let items = List[Derived]()
items.Add(Derived{})
Console.WriteLine(Probes.CountAny[Derived](items))

// GS0159
let entries = map[string, Derived]{}
entries["k"] = Derived{}
Console.WriteLine(Probes.CountAnyMap[string, Derived](entries))
```

```
error GS0159: Cannot find function CountAnyMap.
    Console.WriteLine(Probes.CountAnyMap[string, Derived](entries))
```

## Why this is the asymmetry

Both calls are the same shape: a same-compilation class element, at an **inferred generic slot**, with the type arguments given EXPLICITLY. An inferred slot is exactly what the ADR-0004 erasure exists to serve — a `List[Derived]` reaches `CountAny[T](List<T>)` because the slot's `object` came from erasure, which is what `ClrOverloadResolution.IsErasedGenericParameterSlot` is for.

The `map` spelling does not get there. `map[string, Derived]` presents as `Dictionary<string, ImportedBase>` (the imported-base surrogate from `MemberLookup.TryProjectErasedClrType`), not as `Dictionary<string, object>`, so it never looks like an erased slot's shape and the candidate is not applicable.

That surrogate difference between the `List` spelling and the `map` spelling is the same one #4006 turns on; there it made a call bind that should not, here it makes a call fail that should bind. This one is not a soundness problem — nothing wrong is emitted — but it is a completeness gap in the same place, and it means the two spellings of "a collection of a same-compilation class" behave differently at an imported generic method.

## Controls

- `map[string, int32]` at `CountAnyMap[string, int32]` — binds.
- `List[Derived]` at `CountAny[Derived]` — binds (the row above).
- Explicit vs inferred type arguments makes no difference.

## Expected

`map[string, Derived]` reaches `CountAnyMap[K, V](Dictionary<K, V>)`, closed over the real `Derived`, exactly as `List[Derived]` reaches `CountAny[T](List<T>)`.

## Notes

- Not channel business, so no ADR-0174 erratum.
- The #4006 PR's fixture carries the `List` spelling as a green row and names this issue where the `map` row would otherwise sit.

### PR DESCRIPTION
**Pull request by DavidObando**
Fixes #4013
Fixes #4016

Two overload/member-resolution issues. They are **unrelated** — measured, not assumed. #4013 is candidate *collection* (`MemberLookup.SafeGetMethodsIncludingSelfAndInterfaces`'s interface walk); #4016 is the explicit type-argument *placeholder* (`ExpressionBinder.Calls.Invocation.TryResolveExplicitMethodTypeArgs`). Neither fix touches the other's code, and each was witnessed independently. One branch, two commits.

Both repros were re-verified on `main` @ `a09f4e1b` before anything was written.

---

## #4013 — root cause

`MemberLookup.SafeGetMethodsIncludingSelfAndInterfaces` ends with a walk whose own comment says it is there for DEFAULT interface methods, but it admitted *every* interface member, abstract ones included. `List<T>` implements the non-generic `System.Collections.IList`, whose `Add(object)` accepts anything, so when the argument did not fit the generic `Add(T)`, **candidate collection** — not overload resolution "falling through" — offered the explicit implementation, silently widening the call site to `object`. `List[int32]().Add("x")` compiled and threw `ArgumentException`.

The rule that matches C#: on a class receiver, admit an interface member only when it is **non-abstract** (a genuine DIM). A class must implement every abstract interface member; implemented *implicitly* its own public method is already in the candidate set, implemented *explicitly* C# says it is off the surface. An **interface** receiver keeps the full walk, since a base interface's members really are members of the derived interface. `Type.GetInterfaceMap` throws under the `MetadataLoadContext` reference assemblies load in (used nowhere in this repo for that reason), and reconstructing dotted `Namespace.IFace<T>.Method` metadata names would be fragile — neither is needed.

### #4013 — blast radius, and the legitimate reliance

`rg` cannot find "calls that resolve to an explicit member", so an instrumented compiler logged every drop the rule makes while compiling the whole `samples/` + `e2etests/` `.gs` corpus.

**27 drops, and every one had another candidate of the same name already on the type's own surface** (`onlyCandidate=False` on all 27): `IList.Add(object)`, `IDictionary.Add(object, object)`, `ICollection<KeyValuePair<K, V>>.Add`, `IFormattable.ToString(string, IFormatProvider)`. The corpus still compiles unchanged. Nothing in it depended on an explicit member as its only candidate.

The reliance the corpus did *not* show, the test suite did — **three tests, reported individually because each is a different dependency**:

1. **`Issue3096CollectionSpreadEmitTests.FieldPropertyAndCollectionSpreads_RunAndVerify`** — `Dictionary[string, int32](){ ...pairs }` fills through the explicitly-implemented `ICollection<KeyValuePair<K, V>>.Add`, and lowering emits that call *through the interface*. Narrowing the collection-literal `Add` probe reported `GS0369` ("no accessible 'Add' method or settable indexer").
2. **`Issue3096CollectionSpreadEmitTests.UserDefinedSpreadConversions_ArrayAndCollection_RunAndVerify`** — restricting the exemption to GENERIC interfaces (which would also have closed the literal hole, since `IList` is non-generic) broke this: a `[]Celsius` spread into a `List[float64]` cannot match `Add(double)` through its user-defined conversion, because a same-compilation struct has no CLR type while binding, so the argument erases to `object` and only `IList.Add(object)` accepted it.
3. **`Issue2918InlineLambdaErasedReceiverTests.ImportedGenericReceiverMethods_TargetInlineLambdas_VerifyLoadAndRun`** — `List[System.Action[Mode]].Add((item Mode) -> …)` for a same-compilation enum. Traced:

   ```
   CANDSITE type=System.Collections.Generic.List`1[System.Action`1[System.Object]]
            name=Add cands=1 erasedArg=True args=[(Mode) -> void]
   ```

   The receiver is built over the flat `System.Object` placeholder of the generic-CONSTRUCTION path and presents as `List<Action<object>>`, while the lambda erases the enum to `int` and presents as `Action<int>` — so the type's own `Add(Action<object>)` is inapplicable and only `Add(object)` ever accepted it. **That is #4016's defect one site over**, and repairing it there is out of scope here.

So the member is kept only for (a) a **synthesized collection-initializer `Add`** and (b) an argument carrying a **same-compilation type**. Both turn on something the *call site* has rather than on the member, which is why the reported hole — a genuine `string` at a genuine `int32` — closes while `List[int32]{"x"}` and the same-compilation-argument form stay open. Those are filed as **#4028**, with the suggestion that fixing the generic-construction placeholder the way this PR fixes the method-type-argument one removes the *reason* for exemption (b).

### #4013 — what a call with no other candidate reports

Where the explicit member was the only candidate of that name, the call used to compile and now has nothing to bind to. `GS0159 Cannot find function Contains` is what a *misspelling* reports, so a new **`GS0577`** names the member, the interface that declares it, and the way to reach it:

```
error GS0577: Type 'map[string,int32]' has no member 'Contains' of its own.
'Contains' is declared by the interface 'ICollection<KeyValuePair<String, Int32>>',
which 'map[string,int32]' implements explicitly, so it is not part of the type's
own surface. Reach it through an interface-typed receiver instead (issue #4013).
```

`MemberLookup.TryFindInterfaceOnlyInstanceMethod` is **uncached** and consulted only on that error path, so the memoized candidate lookup on the hot path is untouched. It fires only when the class surface is empty for that name — an inapplicable overload on a type that *does* expose the name keeps `GS0159`.

### #4013 — a correction to the issue

The issue's Expected section asks for `GS0154` naming `int32` and `string`. Measured: **`GS0159` is what an inapplicable imported overload reports on this path**, before and after. The control `Stack[int32]().Push("x")` — whose `Push(T)` has no non-generic sibling and never had this hole — reports `GS0159` too. The fix makes `List.Add` behave *exactly* like that control, which is the real bar; the control is pinned as a fixture row. [Posted on the issue.](https://github.com/DavidObando/gsharp/issues/4013#issuecomment-5559812441)

---

## #4016 — root cause

Two projections of one class that disagree. `MemberLookup.TryProjectErasedClrType` — which every structural argument spelling goes through — erases a same-compilation class to its IMPORTED BASE when it has one (`class Derived : ImportedBase` arrives as `ImportedBase`) and to `object` only when it has none. `TryResolveExplicitMethodTypeArgs` closed the candidate over a flat `System.Object` placeholder regardless (issue #320). So a `Dictionary<string, ImportedBase>` argument was ranked against a `Dictionary<string, object>` parameter — invariant, no conversion, no applicable candidate:

```
PRE arg[0] param=Dictionary`2[System.String,System.Object]
           arg=Dictionary`2[System.String,HelperLib.ImportedBase]
           conv0=None structProj=False
CAND System.String CountAnyMap[String,Object](Dictionary`2[System.String,System.Object]) ok=False
```

The `List` spelling was green only by accident: it takes the `ImportedTypeSymbol` branch into `TryBuildErasedClosedGeneric`, whose component eraser (`ProjectSymbolicArgToErasedClr`) has **no user-class arm** and answers `object` — exactly what the flat placeholder produced, so those two already agreed.

**Fix:** project the explicit type argument the same way the arguments are projected. This is the correction #3087 already made one site over in `ExpressionBinder.Calls.cs` for symbolic *tuple* type arguments. `TryProjectErasedClrType` already answers `object` for a type parameter, an interface and a base-less class, so every case that used to reach the flat placeholder still does.

Nothing is loosened — **#4006's rejections stand**: an erased class surrogate still does not satisfy a GENUINE (non-erased) `List<ImportedBase>` or `Dictionary<string, ImportedBase>` slot in either spelling. Those are the rejected rows in the fixture.

### #4016 — a correction to the issue

A 20-case matrix on `main` shows the stated boundary is wrong in three ways. All three are pinned as fixture rows. [Posted on the issue.](https://github.com/DavidObando/gsharp/issues/4016#issuecomment-5559809159)

| claim in the issue | measured |
|---|---|
| "explicit vs inferred type arguments makes no difference" | it is the **whole** difference — inferred always bound |
| "a same-compilation class" | one with **no imported base** always bound (its erasure was already `object`) |
| a `map`-versus-`List` asymmetry | **not `map`-specific** — `[]Derived` and `[N]Derived` at a `T[]` slot failed identically |

---

## Out of scope, filed

- **#4026** — naming a BASE of the real element as the explicit type argument (`CountAny[ImportedBase]` on a `List[Derived]`) compiles and runs but emits IL ILVerify rejects (`StackUnexpected`). Pre-existing, unchanged. A [follow-up comment](https://github.com/DavidObando/gsharp/issues/4026#issuecomment-5559912994) records that the same hole reaches the **inference** path: the issue's own control `Probes.CountAnyMap(entries)` on a `map[string, Derived]` also fails ILVerify, because inference reads `V` off the argument's surrogate. **Note the direction:** after this PR the *explicit* map spelling verifies (it emits over the real `Derived`, recovered from `typeArgSymbols`) while the *inferred* one still does not. The fixture therefore carries only the slice spelling as its inferred green row.
- **#4028** — the collection-literal and same-compilation-argument forms of #4013's hole, with the two exemptions above documented and a suggested fix order.

## Docs

`GS0577`'s row is byte-identical in `docs/diagnostics.md` and `website/docs/ref/diagnostics.md` (`DiagnosticIdUniquenessTests`). The #4013 breaking change and the #4016 fix are in `website/docs/release-notes.md`. `website/docs/ref/spec.md`'s **Overload resolution** section documents candidate collection as step (1), which is exactly the step #4013 changes, so it gains a sentence: an explicitly-implemented interface member is not part of the implementing type's own surface and is not collected for an ordinary call, while a default-interface method the type does not re-declare is, and an interface receiver still collects its base interfaces' members. #4016 needs no spec change — the erasure placeholder is an implementation detail the spec does not state. No ADR-0174 erratum, since neither issue is channel business.

## ADR-0154 witnesses

Run as suites — revert `src/` to `a09f4e1b`, rebuild, run the filter, capture diagnostics, restore, rebuild.

**#4013** — `dotnet test --filter FullyQualifiedName~Issue4013`

| row | pre-fix diagnostic |
|---|---|
| `the-reported-repro-a-string-does-not-reach-ilist-add-object` | *compiled, no diagnostic* (threw `ArgumentException` at run time) |
| `a-dictionary-does-not-reach-idictionary-add-object-object` | *compiled, no diagnostic* |
| `an-explicit-implementation-with-no-sibling-reports-gs0577` | *compiled, no diagnostic* |
| `map-contains-had-no-other-candidate-and-now-reports-gs0577` | *compiled, no diagnostic* |

**4 red / 7 green before, all 11 green after.**

**#4016** — `dotnet test --filter FullyQualifiedName~Issue4016`

| row | pre-fix diagnostic |
|---|---|
| `a-map-of-a-derived-class-reaches-an-inferred-dictionary-slot` | `error GS0159: Cannot find function CountAnyMap.` |
| `a-derived-class-in-the-key-position-reaches-the-slot-too` | `error GS0159: Cannot find function CountAnyMap.` |
| `a-slice-of-a-derived-class-reaches-an-inferred-array-slot` | `error GS0159: Cannot find function CountArray.` |
| `a-fixed-length-array-of-a-derived-class-reaches-the-same-slot` | `error GS0159: Cannot find function CountArray.` |

**4 red / 6 green before, all 10 green after.**

**Neighbours** — `Issue4013|Issue4016|Issue3096|Issue2918|Issue2889|Issue4006`: **8 red / 56 green before, all 64 green after.**

## Tests

New fixtures execute **and** IL-verify, modelled on `Issue4006ErasedClassSurrogateApplicabilityTests`. Rejection rows and green rows both.

- `Issue4013ExplicitInterfaceMemberCandidacyTests` — 11 tests. Rejections: the reported repro, the `Dictionary`/`IDictionary` sibling, and both `GS0577` shapes. Green: the type's own members, `cast[IList](ys).Add(7)` reaching the explicit member (the issue's own "Expected"), a genuine **DIM** still being a candidate on a class receiver, an **interface receiver** still reaching base-interface members, an **implicitly** implemented member still binding on the class, and iteration + collection literals. Plus the `Stack[int32]().Push("x")` control pinning the `GS0159` equivalence.
- `Issue4016ExplicitTypeArgumentErasureTests` — 10 tests. Four red→green rows (map value, map key, slice, fixed-length array), four green-before rows (the `List` spelling the fix re-routes, inferred, a base-less class, primitives), and two `#4006` rejections that must stay rejected. Every row IL-verifies.

`Issue4006ErasedClassSurrogateApplicabilityTests`' comment naming #4016 where the map row would sit is updated to point at the new fixture.

Suite: `Overload|Member|Interface|Explicit|Generic|Map|List|Collection|Conversion|Issue2889|Issue4006|Issue3989|Issue4000|Issue3096|Issue2918|Issue4013|Issue4016` — **1916 passed, 0 failed.** (`Issue3764CrossContextValueTypeCallShapeTests` and `Issue3755PinningShapeTargetFrameworkTests` are excluded as known-environmental here — the `NETStandard.Library.Ref` targeting pack is absent on this machine.)

---

## Review feedback (`7d94fcfa`)

Two Copilot findings. One was a real defect; the other a real mechanism that does not fire, guarded anyway.

### 1. `GS0577` misfired when no excluded member could accept the call — real defect, fixed

Reproduced before changing anything: `map[string, int32]{}.Contains(1, 2)` reported `GS0577` telling the author to reach `Contains` through an interface-typed receiver, when every `Contains` on `Dictionary<K, V>` is unary. Dead-end advice is worse than the generic `GS0159` it replaced.

`MemberLookup.TryFindInterfaceOnlyInstanceMethod` now takes the bound arguments' erased CLR types and ranks the excluded members through `ClrOverloadResolution.Resolve`, selecting `GS0577` only when one is applicable (an ambiguity counts).

| call | before | after |
|---|---|---|
| `map[string, int32]{}.Contains(1, 2)` | `GS0577` (dead end) | **`GS0159`** |
| `Greeter{}.Secret(1)` vs parameterless `IHidden.Secret()` | `GS0577` | **`GS0159`** |
| `map[string, int32]{}.Contains("k")` | `GS0577` | `GS0577` (still correct) |

**A second bug the finding uncovered:** ranking also picks the *right* interface to name. `d.Contains("k")` previously reported `ICollection<KeyValuePair<String, Int32>>` — first in metadata order, and whose unary `Contains` does not accept a `string`. It now reports `IDictionary`, whose `Contains(object)` does, so `cast[IDictionary](d).Contains("k")` is advice that actually compiles.

Both examples added as fixture rows expecting `GS0159`. The finder stays uncached and on the error path only.

### 2. Explicit enum type arguments — mechanism real, does not fire; guarded

The review is right that `TryProjectErasedClrType` maps `EnumSymbol` → `typeof(int)` (`MemberLookup.cs:276`), that `int` fails `where TEnum : Enum`, and that `TryCloseOverUserValueTypePlaceholders` only substitutes for non-value-type placeholders. But `TryResolveExplicitMethodTypeArgs` tests `ta.ClrType != null` *before* that branch, and a same-compilation `EnumSymbol` carries a non-null `ClrType` — so a direct enum type argument never reaches the projection.

```
dotnet test --filter "FullyQualifiedName~Issue1599|FullyQualifiedName~Issue1601"
Passed!  -  Failed: 0, Passed: 8, Skipped: 0, Total: 8
```

| call over a same-compilation `enum Color` | this branch | parent `a09f4e1b` |
|---|---|---|
| `Enum.TryParse[Color]("Green", out parsed)` | binds, runs, prints `Green` | same |
| `Enum.GetName[Color](Color.Red)` | `GS0159` | **`GS0159` — identical, so pre-existing** |

The guard is applied regardless: a direct `EnumSymbol` keeps the established `System.Object` placeholder, and the projected erasure serves only the same-compilation **class** case #4016 is about. The branch should state its intent rather than lean on `EnumSymbol.ClrType` staying non-null.

**Coverage, honestly:** `Issue1601GenericEnumTryParseForwardTests` *was* in the broad filter already run (it matches `~Generic`). `Issue1599EnumTryParseOutVarTests` was **not** — my filter had no `Enum` term. That was a gap in the filter, not a failure I ignored. `Enum` is now a standing term.

### Housekeeping

- The `GS0577` row is **byte-identical** in `docs/diagnostics.md` and `website/docs/ref/diagnostics.md`, verified with `cmp` (the message text did not change, so neither file moved in this commit).
- Local build re-run: **0 warnings, 0 errors**.
- Suites after review: `Issue4013|Issue4016|Issue1599|Issue1601|Issue3096|Issue2918|Issue2889|Issue4006` — **74 passed, 0 failed**. Broad filter with `Enum` added — **2074 passed, 0 failed** (was 1916; the enum terms pull in 158 more).

---

## CI regression and its fix (`11f3d410`)

The `cs2gs-code-exploder` gate went red on `7d94fcfa`: **15/17 apps green**, two failing with the same diagnostic.

```
GS0159 — Cannot find function AddScheme.
  src/CodeExploder.Gateway/Program.gs (79,10)
  .AddScheme[SharedGateOptions, SharedGateAuthenticationHandler](SharedGateAuthenticationHandler.SchemeName, (o SharedGateOptions) -> {
```

Reproduced locally (same two fingerprints), then **bisected**: reverting #4016's placeholder line alone turns the Gateway app GREEN, so that line is the cause.

### Root cause: the projection is an applicability aid, not a claim about constraints

#4016 closes an explicit type argument over the same erasure the *arguments* present, so a same-compilation class arrives as its imported base and applicability compares like with like. A **constraint** is a different question, and the surrogate leaks into *another* type parameter's constraint whenever that constraint mentions this one:

```
AddScheme[TOptions, THandler]
  where TOptions : AuthenticationSchemeOptions, new()
  where THandler : AuthenticationHandler[TOptions]

class SharedGateOptions : AuthenticationSchemeOptions
class SharedGateAuthenticationHandler : AuthenticationHandler[SharedGateOptions]
```

`SubstituteClrType` put the surrogate into the constraint, so it read `AuthenticationHandler<AuthenticationSchemeOptions>`, while the handler's own base chain still erases to `AuthenticationHandler<object>` — invariant, so `UserReferenceTypeErasedSymbolSatisfiesBaseConstraint` said no and the candidate was dropped. The repair path (`TryCloseOverUserReferenceTypePlaceholders`) is gated behind `SatisfiesGenericConstraints` passing first, so it never ran.

This is the same "two erasers disagree" disease #4016 is about, one layer down: the constraint side still uses `ProjectSymbolicArgToErasedClr`'s `object`, while the placeholder side now uses `TryProjectErasedClrType`'s imported base.

### Fix

Constraints are asked on the `object`-**normalised** vector. `NormaliseErasedTypeArgsForConstraintCheck` puts every position whose recovered symbol has no CLR type back to the reference-context `object` — the same test `RejectConstraintFailureOrThrowCompilerInvariant` uses — so the check asks exactly what it asked before #4016, while the projected vector keeps doing its own job in the closed method's parameter types. It returns the original array when nothing needs normalising, so the common path allocates nothing.

This is the **general** form of review finding 1, which is why the two rules are kept separate rather than merged:

- the `EnumSymbol` guard says *do not project this symbol kind* — a no-op in practice, since an `EnumSymbol` carries a non-null `ClrType`;
- this says *never let a projection reach a constraint* — the rule that actually fires, covering every symbol kind, enums included.

### Verification

Gate re-run locally: **17/17 apps, 0 gaps**, `code-exploder C# and 17-project migrated G# validation passed.`

### Why there is no fixture row for it

Every reduction of this shape hits **#4032** first: a G# class deriving from a *constrained* imported generic base reports `GS0149: Type 'Handler' is not generic`, measured identical on `main` and on this branch. So the synthetic form of `SharedGateAuthenticationHandler : AuthenticationHandler[SharedGateOptions]` cannot be written yet; it is filed, and named in `Issue4016…Tests`' remarks. The gate is the CI-enforced regression test in the meantime.

### Rebase

Rebased onto `main` @ `dfe196e4` (#4029/#4030 merged). One trivial conflict, in `website/docs/release-notes.md`: main added the #4012/#4011/erratum-46 bullets after the same #3998 anchor my #4013 bullet follows. Resolved by keeping main's text verbatim and re-inserting mine after it. Nothing else conflicted.

### Counts after the fix

- `Issue4013|Issue4016|Issue1599|Issue1601|Issue3096|Issue2918|Issue2889|Issue4006|Issue4012|Issue4011` — **101 passed, 0 failed**.
- Broad targeted filter (now also `Enum`, `Constraint`, `Issue4012`, `Issue4011`) — **2133 passed, 0 failed**.
- Local build: **0 warnings, 0 errors**.
- code-exploder gate: **17/17**.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01UVZ9GDN9g4NVF47GRNpWkL

### CODE REVIEW

File: src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs [hunk 1]
```diff
@@ -105,11 +105,39 @@ private bool TryResolveExplicitMethodTypeArgs(TypeArgumentListSyntax? typeArgume
...
+                // a type parameter, an interface and a base-less class, so
+                // every case that used to reach the flat placeholder still does.
+                //
+                // This is the same correction #3087 made one site over in
+                // `ExpressionBinder.Calls.cs`, which stopped flattening a
+                // symbolic TUPLE type argument to `object` for exactly this
+                // reason.
+                resolved[i] = MemberLookup.TryProjectErasedClrType(ta, out var erasedTypeArg)
+                    ? scope.References.MapClrTypeToReferences(erasedTypeArg)
+                    : scope.References.GetCoreType("System.Object");
```
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs]: Good catch on the mechanism — it is real, and I've guarded it. But measured, it does not fire, and the two named suites are green on this branch:

```
dotnet test --filter "FullyQualifiedName~Issue1599|FullyQualifiedName~Issue1601"
Passed!  -  Failed: 0, Passed: 8, Skipped: 0, Total: 8
```

**Why it doesn't fire.** `TryResolveExplicitMethodTypeArgs` tests `ta.ClrType != null` *before* reaching the branch you flagged, and a same-compilation `EnumSymbol` carries a non-null `ClrType` — so a direct enum type argument never reaches `TryProjectErasedClrType` and keeps the reference-context mapping it always had. Every step you describe downstream is accurate (`TryProjectErasedClrType` does map `EnumSymbol` → `typeof(int)` at `MemberLookup.cs:276`, and `TryCloseOverUserValueTypePlaceholders` does only substitute for non-value-type placeholders); the path just isn't entered.

Direct probe, `Enum.TryParse[Color]` and `Enum.GetName[Color]` over a same-compilation `enum Color`:

| call | this branch | parent `a09f4e1b` |
|---|---|---|
| `Enum.TryParse[Color]("Green", out parsed)` | binds, runs, prints `Green` | same |
| `Enum.GetName[Color](Color.Red)` | `GS0159` | **`GS0159` — identical** |

So the one enum call that does fail was already failing before this branch; it is not a regression here.

**Guard applied anyway**, because the branch should state its intent rather than lean on `EnumSymbol.ClrType` staying non-null — that is an invariant a future change could break silently, and the failure mode would be exactly the one you describe. A direct `EnumSymbol` now keeps the established `System.Object` placeholder, and the projected erasure serves only the same-compilation **class** case #4016 is actually about (every row of the `Issue4016` fixture is a class).

**Coverage, honestly:** `Issue1601GenericEnumTryParseForwardTests` *was* inside the broad filter I ran (it matches `~Generic`, so it was among the 1916 passing). `Issue1599EnumTryParseOutVarTests` was **not** — my filter had no `Enum` term. That was a gap in my filter, not a passing test I ignored. `Enum` is now a standing term in the filter and both suites are run explicitly.

Fixed in `7d94fcfa`.

File: src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs [hunk 2]
```diff
@@ -3936,6 +4001,30 @@ bool CheckUserClassInterface(Type source, Type target) =>
...
+        // the author of `map[string, int32]{}.Contains(k)` gets the very same
+        // message a misspelled member produces. Only reached on the error path,
+        // and only when the receiver's own surface has no member of this name
+        // at all: an inapplicable overload on a type that DOES expose the name
+        // (`List[int32]().Add("x")`) stays GS0159, which is what an imported
+        // member with no interface sibling (`Stack[int32]().Push("x")`) already
+        // reported before this change.
+        if (receiver?.Type is { } explicitIfaceRecvType
+            && MemberLookup.TryProjectErasedClrType(explicitIfaceRecvType, out var explicitIfaceRecvClr)
+            && MemberLookup.TryFindInterfaceOnlyInstanceMethod(explicitIfaceRecvClr, methodName, out var declaringIfaces))
```
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs]: You're right, and this was a real defect — fixed in `7d94fcfa`. Reproduced exactly as you describe before changing anything:

```gsharp
let d = map[string, int32]{}
Console.WriteLine(d.Contains(1, 2))
```
```
error GS0577: Type 'map[string,int32]' has no member 'Contains' of its own.
'Contains' is declared by the interface 'ICollection<KeyValuePair<String, Int32>>',
... Reach it through an interface-typed receiver instead (issue #4013).
```

Every `Contains` on `Dictionary<K, V>` is unary, so that advice was a dead end — worse than the generic `GS0159` it replaced, which is the whole reason to have a specific diagnostic.

`MemberLookup.TryFindInterfaceOnlyInstanceMethod` now takes the bound arguments' erased CLR types and ranks the excluded members through `ClrOverloadResolution.Resolve`, reporting `GS0577` only when one of them is applicable (an ambiguity counts — at least one applies). Otherwise `GS0159` stands.

| call | before | after |
|---|---|---|
| `map[string, int32]{}.Contains(1, 2)` | `GS0577` (dead-end advice) | **`GS0159`** |
| `Greeter{}.Secret(1)` vs parameterless `IHidden.Secret()` | `GS0577` | **`GS0159`** |
| `map[string, int32]{}.Contains("k")` | `GS0577` | `GS0577` (still correct) |

**A second bug your finding uncovered.** Ranking also picks the *right* interface to name, which the name-only version got wrong even when it was entitled to fire. For `d.Contains("k")` it previously reported `ICollection<KeyValuePair<String, Int32>>` — first in metadata order, and whose unary `Contains(KeyValuePair<…>)` does *not* accept a `string`. It now reports `IDictionary`, whose `Contains(object)` does, so the suggested `cast[IDictionary](d).Contains("k")` is advice that actually compiles. The fixture asserts the id rather than the text, so this tightening is visible in the diagnostic itself.

Both of your examples are added as fixture rows expecting `GS0159`:
`an-inapplicable-arity-keeps-gs0159-rather-than-gs0577` and
`an-inapplicable-explicit-member-keeps-gs0159-rather-than-gs0577`.

The finder stays uncached and on the error path only, so the hot-path candidate lookup is still untouched. Suite `Issue4013|Issue4016|Issue1599|Issue1601|Issue3096|Issue2918|Issue2889|Issue4006`: 74 passed, 0 failed.

File: src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Invocation.cs]: Follow-up: this line **did** cause a CI regression — but through constraints, not the enum path. Fixed in `11f3d410`.

The `cs2gs-code-exploder` gate went red (15/17), both failures the same:

```
GS0159 — Cannot find function AddScheme.
  src/CodeExploder.Gateway/Program.gs (79,10)
  .AddScheme[SharedGateOptions, SharedGateAuthenticationHandler](...)
```

Reproduced locally with the same fingerprints, then bisected: reverting this one line alone turns the app GREEN, so it is the cause.

**Root cause — your chain, one symbol kind wider.** The projection leaks into *another* type parameter's constraint whenever that constraint mentions this one:

```
AddScheme[TOptions, THandler]
  where TOptions : AuthenticationSchemeOptions, new()
  where THandler : AuthenticationHandler[TOptions]

class SharedGateOptions : AuthenticationSchemeOptions
class SharedGateAuthenticationHandler : AuthenticationHandler[SharedGateOptions]
```

`SubstituteClrType` put the surrogate into the constraint, so it read `AuthenticationHandler<AuthenticationSchemeOptions>`, while the handler's own base chain still erases to `AuthenticationHandler<object>` — invariant, so `UserReferenceTypeErasedSymbolSatisfiesBaseConstraint` said no and the candidate was dropped. Exactly "the projected argument fails the constraint and cannot be repaired", as you put it — the repair path (`TryCloseOverUserReferenceTypePlaceholders`) is gated behind `SatisfiesGenericConstraints` passing first, so it never ran.

**Fix — the general rule, which is why I did not merge it with the enum guard.** Constraints are now asked on the `object`-**normalised** vector (`NormaliseErasedTypeArgsForConstraintCheck`): every position whose recovered symbol has no CLR type goes back to the reference-context `object`, which is exactly the question this check asked before #4016. The projected vector keeps doing its own job in the closed method's parameter types.

- The `EnumSymbol` guard says *don't project this symbol kind* — a no-op in practice, since an `EnumSymbol` carries a non-null `ClrType`.
- This says *never let a projection reach a constraint* — the rule that actually fires, covering every symbol kind, enums included.

They are different statements, so I kept both rather than collapsing them; the enum guard is now belt-and-braces over a rule that already covers it.

**Verification:** gate re-run locally → **17/17 apps, 0 gaps**, "code-exploder C# and 17-project migrated G# validation passed."

**Why there is no fixture row:** every reduction of this shape hits #4032 first — a G# class deriving from a *constrained* imported generic base reports `GS0149: Type 'Handler' is not generic`, measured identical on `main` and this branch — so the synthetic form of `SharedGateAuthenticationHandler : AuthenticationHandler[SharedGateOptions]` cannot be written yet. Filed separately, and named in the fixture's remarks; the gate is the regression test in the meantime.

Also rebased onto `main` @ `dfe196e4` (#4029/#4030 merged); one trivial release-notes conflict, resolved by keeping main's bullets and re-inserting mine.
