### ISSUE TITLE
gsc: conversion call on a nested imported type fails to bind (GS0159, from #3745)

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#3749]
Split out of #3745 (family F5). Found in the migrated `test/Compiler.Tests` compile wall; 1 of that app's 20 errors.

The G# conversion-call form `T(expr)` does not resolve a **nested** imported type, so a C# cast to a nested enum translates to something gsc cannot bind.

## Repro (gsc, `0.4.349+cec369958b`)

```gs
import System
import System.Diagnostics

func main() {
    let flags = DebuggableAttribute.DebuggingModes(2)
    // error GS0159: Cannot find function DebuggingModes.
    Console.WriteLine(flags)
}
```

`DebuggableAttribute.DebuggingModes` is a nested enum. The unnested spelling of a conversion call (e.g. `int32(x)`, `SomeTopLevelEnum(x)`) binds today.

## Current evidence in the corpus

`test/Compiler.Tests/Issue2920ReleaseJitOptimizerTests.cs:78`:

```csharp
Assert.Equal((DebuggableAttribute.DebuggingModes)expectedFlags, debuggable!.DebuggingFlags);
```

cs2gs faithfully translates the cast to the conversion-call form, migrated to `Issue2920ReleaseJitOptimizerTests.gs:49,46`:

```gs
Assert.Equal(DebuggableAttribute.DebuggingModes(expectedFlags), debuggable!!.DebuggingFlags)
```

which reports `GS0159 Cannot find function DebuggingModes.`

The translation looks correct, so this reads as a gsc binder gap (a member-access expression in conversion-call position is only probed as a function, never as a nested type). Worth confirming the layer before fixing: if the nested conversion-call form is deliberately unsupported by the grammar, cs2gs should emit `cast[…]` instead.

## Not a regression

Adjacent to but distinct from the solved nested-type family (#3660 / PR #3662), which was nested-type → enclosing-`shared` **calls**; this is the conversion-call direction.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Nng28yiBdPVdeML7mSZphs

**Comment by DavidObando** [comment]
**Scope correction from PR #3758.** Nesting makes this gap *visible* rather than causing it.

Nested-type resolution (#569) already worked — the type resolves fine. The namespace-qualified form fails on `main` too:

```
System.DayOfWeek(2)
```

So the gap belongs to the **dotted binding path**, not to nested types specifically.

Root cause: `ExpressionBinder.TryBindQualifiedClrConstructorCall` called `FinishClrConstructorBindingFailure` **without** the `conversionTarget` that all four sibling call sites supply, making the ADR-0047 §6 conversion fallback unreachable. Additionally, that helper's three arms enumerate specific conversion *kinds* (checked reference, unboxing, delegate) — an enum matched none — so the general arm the simple-name path already applies was added, gated on `Conversion.Classify(...).Exists` so unconvertible arguments still error.

**Not a regression of #3660 / PR #3662**: #3662 added lexical outward walking in `BindCallExpression` so a nested type's *body* reaches an enclosing type's `shared` members. This is the opposite direction — a nested type named as a conversion *target* from outside — in a different file.
