### ISSUE TITLE
Binder: G# class implementing a CLR interface method that returns `Nullable<T>` for value-type T rejected with GS0187

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#638]
## Summary

A G# class that implements a CLR interface whose method returns `Nullable<T>` for some value type `T` (e.g. `int?`, `ConsoleKeyInfo?`, `bool?`) is rejected with `GS0187: Class does not implement interface method` — even when the G# method signature uses the matching `T?` return type.

This is asymmetric with the **nullable reference** case: `string?` returns work fine. Only the `Nullable<T>` (value-type) shape trips the interface-satisfaction check.

Related family: gsharp#573 was about fields satisfying interface properties; this one is about method signatures matching when nullable value types appear in the signature.

## Repro

Sibling C#:
```csharp
namespace Probe.CSharp;

public interface IMaybeInt
{
    int? Try();
}

public interface IMaybeString
{
    string? Try();
}
```

G#:
```gsharp
package Probe
import Probe.CSharp

// Reference-nullable return — ✅ works
type MaybeStringImpl class : IMaybeString {
    func Try() string? {
        return nil
    }
}

// Value-nullable return — ❌ fails with GS0187
type MaybeIntImpl class : IMaybeInt {
    func Try() int32? {
        return nil
    }
}
```

## Observed

```
error GS0187: Class 'MaybeIntImpl' does not implement interface method 'Probe.CSharp.IMaybeInt.Try'.
```

The G# signature `func Try() int32?` should match the C# `int? Try()` — both project to `System.Nullable<int>` at the metadata level. The binder doesn't appear to treat `int32?` in a method declaration as the canonical `Nullable<int>` for interface satisfaction.

## What works in 0.1.509 (for comparison)

```gsharp
// Property with nullable struct setter satisfies interface contract — works
type Impl class : IHasNullableProp {
    Q int32?
}

// Method taking nullable struct as parameter — works
type Impl class : IConsumeNullable {
    func Consume(v int32?) { ... }
}
```

So the gap is specifically the **return type** position.

## Expected

Returning `T?` from an interface-implementing method should satisfy the contract whenever the interface method's return type is `Nullable<T>`. Equivalent to C# `int? Try() => null;` implementing `int? Try()` on an interface.

## Context

`gsc` version: `Gsharp.NET.Sdk/0.1.509`, .NET 10 RTM.

Discovered while porting `tests/Oahu.Cli.Tests/Tui/AppShellTests.cs` — `AppShell.IKeyReader` declares `ConsoleKeyInfo? ReadKey()`. The G# port needs a test fake implementing this interface; the natural shape is rejected, and there's no workaround (returning a non-nullable wrapper changes the interface contract). This blocks 3 Run-loop tests in `AppShellTests.cs`.

**Comment by DavidObando** [comment]
✅ Fixed in `Gsharp.NET.Sdk/0.1.514`. Verified end-to-end with the original repro. Closing.
