### PR TITLE
gsc: the imported-type-symbol cache must be load-context sensitive (#3826)

### LINKED ISSUE #3826: gsc: a CLR Type from one compilation reaches a later compilation's binder through a process-wide cache
Split out of #3818, where it was the underlying cause. #3825 removed the
*duplicate identities* that made it fatal; the leak itself is still there.

## What was observed

While reproducing #3818 (`Adr0169Gsa0005ParityTests` + `Adr0169AnalyzerTranslationTests`
in one test host, ~50% failure), the GS0159 site was instrumented at
`ExpressionBinder.BindAccessorCall`. On a failing run, for
`baseNode.FirstAncestorOrSelf[FunctionDeclarationSyntax]()`:

```
clr=GSharp.Core.CodeAnalysis.Syntax.SyntaxNode
recvAsmId=42766207  typeArgAsmIds=61859700  sameAsm=False
resolverRecv=64174338  recvIsCurrent=False
recvAlc=<unnamed>  recvIsDefaultAlc=False  recvInResolverList=False
```

The receiver's CLR `Type` came from an **unnamed, non-default
`AssemblyLoadContext` that is not in the current resolver's assembly list** —
i.e. a `DriverReferenceLoadContext` created by an *earlier* compilation in the
same process. The current resolver would have resolved the same full name
(`resolverRecv`) to a different instance, and the explicit type argument did.

Every symbol/member cache reachable from that path is keyed on `Type` or
`Assembly` and is cleared from `ReferenceResolver.Dispose`
(`ImportedTypeSymbol`, `MemberLookup`, `ClrTypeUtilities`, the constructed-type
caches, …), so the exact carrier was not identified. It is worth finding: any
such leak is a silent-wrong-answer hazard of the #3705 load-context family, and
it is not confined to tests — the language server and the analyzer/generator
hosts all run many compilations in one process.

## Why it matters even after #3825

#3825 makes `WithRuntimeReferences` reuse the host's assembly when the path is
already loaded, so the common case now has one identity and a leaked `Type`
is harmless. A compilation that legitimately loads a *different* assembly
privately (a real `/reference:` to a user assembly, cross-targeting) still has
two contexts alive, and a leak between two such compilations would reproduce
the same class of failure — an opaque "Cannot find function X" for a method
that exists, or a silently-taken wrong arm.

## Suggested direction

Add a debug-only invariant to `ReferenceResolver`: any `Type` the binder
receives must belong to an assembly in that resolver's own list. Running the
existing suites with it on should name the carrier in one pass.

Refs #3818, #3825, #3705, #1622.

### PR DESCRIPTION
**Pull request by DavidObando**
Fixes #3826.

#3825 removed the *duplicate identities* that made this fatal. The leak itself
was still there, and #3826 asked for the carrier by name. It is:

> **`ImportedTypeSymbol`'s process-wide cache — specifically its key.**

## How it carries a Type across compilations

```csharp
private static readonly ConditionalWeakTable<Assembly, ConcurrentDictionary<Type, ImportedTypeSymbol>> Cache = new();

var assemblyCache = Cache.GetValue(
    type.Assembly,
    static _ => new ConcurrentDictionary<Type, ImportedTypeSymbol>(TypeIdentityComparer.Instance));
return assemblyCache.GetOrAdd(type, static t => new ImportedTypeSymbol(t));
```

`TypeIdentityComparer` compares by `Type.AssemblyQualifiedName` — deliberately,
for #420, so the emitter collapses one logical type reached by several paths
into one `TypeRef` row. Two copies of the *same file* loaded into two different
`AssemblyLoadContext`s have **identical** assembly-qualified names, so that
comparer cannot tell them apart.

The outer `ConditionalWeakTable` bucket looks like it saves us — it is keyed on
the `Assembly` instance, which does differ per context. It does not, because it
is keyed on **the type's own assembly**, not on the assemblies the type is
*built from*. For a constructed generic whose definition lives in a shared
assembly, both compilations land in the same bucket:

| | `ImmutableArray<SyntaxNode>` from compilation A | …from compilation B |
|---|---|---|
| outer key (`type.Assembly`) | host `System.Collections.Immutable` | **same instance** |
| inner key (AQN) | `…ImmutableArray\`1[[…SyntaxNode, GSharp.Core, …]]` | **same string** |

So `ImportedTypeSymbol.Get(ImmutableArray<B.SyntaxNode>)` returns **A's**
symbol, whose `ClrType` and `TypeArguments` are A's. Every type derived from it
downstream — notably a `for` loop variable's element type — is A's too.

That is exactly the #3818 shape: `baseNode` (element of
`ImmutableArray<SyntaxNode>`) carried the *previous* compilation's `SyntaxNode`
while the explicit type argument `FunctionDeclarationSyntax` came from the
current one, `MakeGenericMethod` threw, `ClrOverloadResolution` dropped the only
candidate per C# §7.5.2, and the call reported "Cannot find function
FirstAncestorOrSelf" about a method that plainly exists.

Introduced by #2341, which changed the cache from a reference-keyed
`ConcurrentDictionary<Type, …>` (cleared on dispose) to this shape.

## Instrumented evidence

Tagging every `TypeSymbol` with a monotonic resolver generation and a creation
stack, then dumping at the GS0159 site on a failing run:

```
=== LeakProbe GS0159-imported:FirstAncestorOrSelf gen=21 symbol=ImportedTypeSymbol ===
  name=GSharp.Core.CodeAnalysis.Syntax.SyntaxNode  alc=<unnamed>
  symbolCreatedInGen=1
  creationStack:
   ImportedTypeSymbol.Get  <- TypeSymbol.FromClrType
   <- MemberLookup.MapOpenClrTypeToSymbolic  <- MemberLookup.GetClrPropertyTypeSymbol
   <- ExpressionBinder.BindAccessorStep
   <- Compilation.Emit  <- Adr0169Gsa0005ParityTests.CompileTranslatedGsa0005
  reportStack:
   ExpressionBinder.BindAccessorCall <- … <- StatementBinder.BindForRangeStatement
   <- Compilation.get_BoundProgram
   <- Adr0169AnalyzerTranslationTests.SemanticModelAnalyzer_TranslatesDeclarationAndOverrideIdioms
```

The **symbol object itself**, not merely a `Type`, was created in generation 1
(`Adr0169Gsa0005ParityTests`) and consumed in generation 21
(`Adr0169AnalyzerTranslationTests`). A bounded BFS from every static field in
`GSharp.Core` — taught to see through `ConditionalWeakTable`, which is where the
first attempt went blind — then produced the retaining path in one line:

```
rootScan: nodes=2061 found=True
  <- GSharp.Core.CodeAnalysis.Symbols.ImportedTypeSymbol.Cache [ConditionalWeakTable`2]
  <- {value} [ConcurrentDictionary`2]
  <- {value} [ImportedTypeSymbol]
```

#3826 predicted "every cache reachable on that path is `Type`- or
`Assembly`-keyed", and that is where the previous investigation stopped. It is
true and it is not sufficient: **being keyed on `Type` only helps if the key
compares by identity.** This one compares by name.

Corollary worth recording: `ImportedTypeSymbol.ClearCache()`, which
`ReferenceResolver.Dispose` calls with a comment claiming it clears the cache,
has been an **empty method** since #2341. That is a documentation defect, not
the bug — and clearing is deliberately *not* the fix (see below).

## The fix

`LoadContextSensitiveTypeComparer`: the same structural identity as
`TypeIdentityComparer`, plus a walk over the type's constituents (element type,
generic arguments) requiring the same `Assembly` **instance** at every position.
Hash stays name-based — a bucketing hint — and equality does the real test, the
same shape as the existing `TypeArgsKey`.

Two instances of one logical type reached by different paths inside a *single*
context still collapse, because a load context returns one `Assembly` instance
per identity, so #420's dedup is preserved. `ImportedTypeSymbol.Cache` is the
only process-wide consumer of `TypeIdentityComparer`; `MetadataTokenCache`'s
dictionaries are instance fields scoped to one emit, and the two
`ExpressionBinder` uses compare against a core-library type by name on purpose.

`ClearCache` stays a no-op. Clearing would only paper over the sequential case
and would leave two *live* resolvers aliasing each other; and the caches
`Dispose` really does clear have a churn hazard (symbols obtained before and
after a clear stop being reference-equal) that is not worth re-adding. The
misleading comments on both sides are corrected instead.

## Reproduction and measurement

`Issue3826CrossCompilationTypeIdentityTests` reproduces the leak
**deterministically in ~0.4s**, with no ordering dependence: it copies
`GSharp.Core.dll` to a path the host has not loaded (so #3825's path-equality
reuse does not apply and each resolver really does mint a private copy), takes
`SyntaxNode` from two successive resolvers, and closes `ImmutableArray<>` over
each.

| test | on `main` | here |
|---|---|---|
| `TwoPrivateReferenceContextsOverTheSamePath_ProduceDistinctTypes` | **passes** (anti-vacuity guard rail) | passes |
| `ConstructedGenericFromASharedAssembly_DoesNotAliasAcrossContexts` | fails | passes |
| `ACachedSymbolNeverHandsBackAnotherContextsTypeArgument` | fails | passes |

The first test is honestly labelled: it asserts only that the two contexts *are*
distinct, which is already true on `main`. It exists so a future change that
silently unified the two copies could not make the other two pass vacuously.

For the original flaky repro — `Adr0169Gsa0005ParityTests` +
`Adr0169AnalyzerTranslationTests` in one host — #3825's reuse **masks** the
symptom without fixing the leak, so measuring against it is meaningless. Both
arms below were run with that masking disabled, via this one-line local edit
(not committed):

```diff
-                Assembly? reused = TryReuseHostLoadedAssembly(fullPath);
+                Assembly? reused = Environment.GetEnvironmentVariable("GS_DISABLE_3825") == "1"
+                    ? null
+                    : TryReuseHostLoadedAssembly(fullPath);
```

```
GS_DISABLE_3825=1 dotnet test tools/cs2gs/Cs2Gs.Tests/Cs2Gs.Tests.csproj --no-build \
  --filter "FullyQualifiedName~Adr0169Gsa0005ParityTests|FullyQualifiedName~Adr0169AnalyzerTranslationTests"
```

| | runs | failures |
|---|---|---|
| without this fix | 10 | **4 (40%)** |
| with this fix | **32** (12 + 20) | **0** |

(#3825 measured the same repro at 18/43 = 42% before its own fix.)

Suites, locally: `Core.Tests` **8598/8598**; `Cs2Gs.Tests` **2664/2665**. The single failure is `Adr0151IfLetExpressionTranslationTests.Issue2819_SameVersionPackedToolAndSdk_CompileTranslatedPatternVariable`, which fails on its first line — `Assert.NotNull(ResolveLocalCs2GsPackage(repoRoot))` — because this worktree has no `out/bin/Release/nupkgs` (it has never run a Release pack). It never reaches the compiler, so it cannot be affected by this change. CI is the authority.

## Relationship to #3830

Same family, different layer, no file overlap — #3830 is the test helper
(emitted fixtures into a collectible context); this is the product cache. They
compose in the right direction: #3830 *increases* the number of distinct
collectible contexts holding same-named types in one process, which is exactly
the input the old name-only key mis-merged and the new key handles. Nothing in
`test/Compiler.Tests/Emit/ConversionEmitTests.cs` was touched here.

## The silent candidate drop — recommendation, not built

`ClrOverloadResolution.EvaluateCandidate` wraps `MakeGenericMethod` in
`catch (ArgumentException) { … return; }` at three sites. That conflates two
unrelated causes:

1. **Generic constraints not satisfied** — a genuine applicability failure.
   C# §7.5.2 says drop it silently. Correct as-is.
2. **Cross-load-context operands** — never a language-level "not applicable".
   It is a violation of the compiler's own type-plumbing invariant, and
   swallowing it converts an internal bug into a user-facing lie about a method
   that exists.

The two are separable *exactly*, without sniffing exception text: before
closing, every element of `typeArgs` must come from the same load context as
`mi.DeclaringType` — the code already reasons about this for the
`MetadataLoadContext` projection a few lines above. Recommendation, as its own
issue rather than in this PR:

- **Recommended:** detect the mismatch explicitly and report a distinct internal
  diagnostic in the `GS9998` ICE family ("cross-load-context operands closing
  `<method>`") instead of dropping. It surfaces the defect at its cause rather
  than as `GS0159` at a distant site. It needs a full-suite run of its own,
  because it turns any remaining silent misbind into a hard error — which is the
  point, but is a behaviour change.
- **Cheap fallback if that is too aggressive:** a `Debug`-only trace at the two
  catch sites recording the method, its declaring type's context, and each type
  argument's context. Zero release cost, and it would have turned this
  investigation from days into one run.
- **Rejected:** making `GS0159` explain why every candidate was dropped — too
  noisy, and it churns a large number of golden diagnostics.

Refs #3818, #3825, #3705, #1622, #2341, #420.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Nng28yiBdPVdeML7mSZphs

### CODE REVIEW

**Comment by DavidObando** [comment]
CI: **35/35 green**, 0 failures (3 publish/deploy jobs skipped as usual).

Two shards worth calling out specifically:

- `tests (cs2gs-remainder)` — the gate this whole line of work is about — **passes**.
- `tests (compiler-emit-remainder)` **passes**. It was red on #3825 for the `ConversionEmitTests` flake filed as #3828; #3830 landed that half, so both halves of the family are now closed at their own layer.

The one local `Cs2Gs.Tests` failure noted in the description (`Issue2819_SameVersionPackedToolAndSdk_CompileTranslatedPatternVariable`) does not reproduce here, confirming it was the missing local `out/bin/Release/nupkgs` precondition in my worktree and not a behaviour failure.
