### ISSUE TITLE
selfmig: triage of the migrated test/Compiler.Tests compile wall — 8 fingerprints, 16 sites, 1 root cause (a variadic carrier's sink contract)

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#3886]
Triage of the migrated `test/Compiler.Tests` compile wall (issue #3501, Track C).

## Measurement

Re-measured on `origin/main` @ `2b58cf48c` — nightly gate run
[33819616178](https://github.com/DavidObando/gsharp/actions/runs/33819616178),
shard 5, `test_Compiler.Tests_.../sdk.build.log`. Unchanged from the earlier
run 33808173710 on `fb3c60ab0`: none of #3871/#3875/#3878/#3881/#3884 touched
this wall.

**8 fingerprints → 16 real sites → 1 root cause.**

Two corrections to the fingerprint summary that motivated this triage: it
listed six "cannot find" fingerprints, but the log has **eight** distinct
messages (`GetParameters` and `Invoke` were missing), and every per-message
count was understated (`GetType` is 4×, not 2×).

All 16 sites are in **one file, one test method, a contiguous 19-line block**:
`test/Compiler.Tests/Emit/Issue2525ImportedIndexerHidingEmitTests.gs` lines
199-217.

```
199,54  GS0154  Parameter 'assemblyPaths' requires a value of type 'string' but was given a value of type 'string?'.
201,37  GS0159  Cannot find function GetType.
202,34  GS0159  Cannot find function GetType.
204,14  GS0159  Cannot find function GetProperties.
207,14  GS0159  Cannot find function GetProperties.
209,38  GS0158  Cannot find member MetadataToken.
209,69  GS0158  Cannot find member MetadataToken.
211,27  GS0159  Cannot find function GetType.
212,58  GS0159  Cannot find function GetMethod.
212,78  GS0159  Cannot find function GetParameters.
213,55  GS0159  Cannot find function GetMethod.
213,79  GS0159  Cannot find function GetParameters.
215,17  GS0159  Cannot find function GetMethod.
215,47  GS0159  Cannot find function Invoke.
216,60  GS0159  Cannot find function GetType.
217,45  GS0159  Cannot find function Compile.
```

## Root-cause table

| cause | sites | layer | new / known / cascade | tractability |
|---|---|---|---|---|
| a variadic carrier's sink contract is read from the promoted parameter, not the emitted `...T` signature | 1 (line 199) | cs2gs translator | **new** (seam left by #1072 + #3644) | fixed in this PR |
| gsc reports `Cannot find function/member` on a member access whose receiver is already error-typed | 15 (lines 201-217) | gsc binder diagnostics | known family (#3842, #3880) — filed separately | not fixed here |

### The 15 reflection errors are NOT a reflection mechanism

They are cascades. Minimal gsc repro, no reflection involved — one real
GS0154 manufactures three "Cannot find" errors:

```gs
package Demo
class Fixture { shared { func Load(paths ...string) []string { return paths } } }
class Caller {
    shared {
        func Go(maybe string?) int32 {
            let loaded = Fixture.Load(maybe)     // GS0154 — the only real error
            let first = loaded[0]
            return first.Length + first.IndexOf("x") + loaded.Length
        }
    }
}
```
```
(16,39): error GS0154: Parameter 'paths' requires a value of type 'string' but was given a value of type 'string?'.
(18,26): error GS0158: Cannot find member Length.
(18,41): error GS0159: Cannot find function IndexOf.
(18,63): error GS0158: Cannot find member Length.
```

`System.Type` / `System.Reflection` member resolution is fine. The clustering
of `GetType`/`GetMethod`/`GetProperties`/`MetadataToken` is an artifact of the
one test method that happens to use reflection heavily downstream of the
poisoned local.

### The GS0154 is not #3859 residue — but #3859's subject is the trigger

The parameter name is the same (`EmittedFixture.LoadTogether(params string[]
assemblyPaths)`, `test/Shared/EmittedFixture.cs`, `<Compile Include>`-linked
into both `Core.Tests` and `Compiler.Tests`), and the guard #3859 worked on is
what tips the fixpoint — but the defect is in a different place and neither
introduced nor reintroduced by #3859.

**Mechanism.** `TranslateParameter`
(`CSharpToGSharpTranslator.Constructors.cs`) deliberately never promotes a
variadic carrier:

```csharp
// Issue #1072: ... (variadic params are never null-compared as a
// whole, so they are excluded).
if (!variadic && promoteNullability)
{
    type = this.PromoteIfUsedAsNullable(type, symbol);
}
```

so `LoadTogether` is always emitted `func LoadTogether(assemblyPaths ...string)`
— element type non-null — however much null evidence exists. `LoadTogether`
opens with `if (assemblyPaths is null) throw`, which IS null evidence, so the
oblivious-nullability fixpoint records `assemblyPaths` as promoted.

The **call** side then asks the same question of the same symbol
(`TargetWillRemainNonNullableReference` → `ShouldPromoteToNullableReference`
in `CSharpToGSharpTranslator.Nullability.cs`), concludes the sink widened to
`...string?`, and suppresses the `!!` bridge — including the expanded-params
element bridge added by #3644. The promoted `result.ContractsPath` (`string?`)
therefore reaches a non-null `...string` slot bare.

Reduced repro, translator-level; the `is null` guard is the entire difference:

```csharp
public static string[] LoadTogether(params string[] assemblyPaths)
{
    if (assemblyPaths is null) { throw new ArgumentNullException(nameof(assemblyPaths)); }
    return assemblyPaths;
}
...
return Fixture.LoadTogether(result.ContractsPath, output);   // result.ContractsPath is promoted string?
```

| guard present | emitted declaration | emitted call site |
|---|---|---|
| yes | `func LoadTogether(assemblyPaths ...string)` | `Fixture.LoadTogether(result.ContractsPath, output)` — **no bridge, GS0154** |
| no  | `func LoadTogether(assemblyPaths ...string)` | `Fixture.LoadTogether(result.ContractsPath!!, output)` — correct |

Same declaration, opposite call sites. The suppression is the bug.

The existing #3644 coverage did not catch it because its fixture calls
`Path.Combine` — an **imported** params target, where
`targetDeclaredInThisCompilation` is false and the promotion clause is never
reached. The defect needs a **source-declared** params parameter, which is
exactly what a `<Compile Include>`-linked shared test fixture is.

## Fix

Mirror the declaration rule on the sink side: a variadic carrier's contract is
whatever its own annotation says, never a promoted one. This also repairs the
DIRECT collection form (`LoadTogether(paths)` binding the parameter itself),
which had the same suppression.

## Also found, filed separately

- gsc cascade masking on error-typed receivers (the 15 sites) — see the
  companion issue.
- cs2gs never widens a params **element** even with direct null evidence: an
  expanded `null` literal argument translates to `Fixture.Load(nil, output)`
  against a `...string` carrier, which gsc rejects. Latent (no site in the
  corpus reaches it), pre-existing, unchanged by this PR.

**Comment by DavidObando** [comment]
Fixed in #3891 (branch `fix/3886-variadic-carrier-sink-contract`, rebased onto `36a147f0f`).

**Anti-vacuity, measured:** with the one-hunk fix reverted to `2b58cf48c` and nothing else changed, the three regression tests report `Failed: 2, Passed: 1` — the two wall shapes fail at `AssertBinds` (the emitted G# does not bind), and the precision guard passes, as it must. With the fix: `Passed: 3`, each one compiling and RUNNING the emitted G# through `EmittedOracle` and asserting the value.

Full `Cs2Gs.Tests` on the fix: **2733 passed, 1 failed** — `Adr0151IfLetExpressionTranslationTests.Issue2819_SameVersionPackedToolAndSdk_CompileTranslatedPatternVariable`, failing at line 346 (`Assert.NotNull(cs2gs)`) because this worktree has no Release `out/bin/Release/nupkgs`. Environment-only, unrelated to the change. On the post-#3882 base, the 63 tests in the affected families (#3886/#3644/#1072/#3865/#3676/#3501-residual) all pass.

Companion issues filed: **#3887** (the 15 cascades) and **#3888** (the params-element gap). `selfmig-baseline.json` untouched.

**Comment by DavidObando** [comment]
Fixed in PR #3891 — migrated `test/Compiler.Tests` compile errors **16 → 0**.

The triage in this issue was the valuable part, and it inverted the framing it started with: the eight fingerprints were **16 real sites, and one root cause with 15 cascades**. There was no reflection defect at all — the `GetType`/`GetMethod`/`GetProperties`/`MetadataToken` clustering was an artifact of the single test method that uses reflection *downstream of a poisoned local*. A four-line gsc repro containing **no reflection whatsoever** reproduced three "Cannot find" errors naming members that demonstrably exist.

Root cause: a variadic carrier's sink contract was read from the **promoted** parameter rather than the emitted `...T` signature. `TranslateParameter` deliberately never promotes a variadic carrier, but `TargetWillRemainNonNullableReference` asked `ShouldPromoteToNullableReference` about that same parameter, saw the `is null` guard, and suppressed the `!!` bridge. #3644's coverage missed it because its fixture uses `Path.Combine`, an **imported** target where the promotion clause is never reached.

It was **not** #3859 residue, despite the same parameter and the same guard — #3859 touched only `Patterns.cs`/`Statements.cs` and never the promotion fixpoint or the sink-contract check.

The 15 cascades are tracked separately as #3887 (member access on an error-typed receiver), fixed in PR #3912.
