### ISSUE TITLE
Binder: cannot construct a nested CLR type via `Outer.Inner()` (GS0159) — works as type clause / base type, fails as construction expression

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#569]
## Summary

A nested CLR type cannot be **constructed** via `Outer.Inner()` — the binder treats `Outer.Inner` as a function call and reports `GS0159: Cannot find function Inner.` This is the remaining facet of gsharp#526 (which fixed nested types as type clauses and as base types in `class : Outer.Inner` declarations).

The 0.1.459 release fixed using a nested type as a **type clause** (`var x Outer.Inner = ...`) and as a **base type** (`type X class : Outer.Inner { ... }`). But the **call/construction expression** path still rejects `Outer.Inner()`.

## Repro

Sibling C#:
```csharp
namespace Probe.CSharp;

public sealed class InstanceOuter
{
    public sealed class NestedFactory { public int Value { get; init; } }
}

public static class StaticOuter
{
    public sealed class NestedFactory { public int Value { get; init; } }
}
```

G#:
```gsharp
package Probe.Tests
import Probe.CSharp
import Xunit

type Probe class {
    @Fact
    func Construct_Nested_From_Instance_Outer() {
        let f = InstanceOuter.NestedFactory()    // GS0159
    }

    @Fact
    func Construct_Nested_From_Static_Outer() {
        let f = StaticOuter.NestedFactory()      // GS0159
    }
}
```

## Observed

```
error GS0159: Cannot find function NestedFactory.
```

## What works in 0.1.459

The binder *knows* the nested type exists — these all work:

```gsharp
// Type clause
var f InstanceOuter.NestedFactory = factory()

// Base type
type Impl class : Outer.INested { ... }

// As return type of a static factory method
static func Make() InstanceOuter.NestedFactory { return ... }
let f = StaticOuter.Make()      // works — receives the nested type via a static helper

// Object-initializer if we have an instance from elsewhere
var copy = OtherInstanceProvider.Get() { Value = 5 }
```

What fails is specifically the construction-expression syntax `Outer.Inner(args)`.

## Expected

`Outer.Inner(args)` should construct the nested type by invoking its constructor, the same way `BareType(args)` does for top-level types. This is the natural way to express `new Outer.Inner(args)` in C# / Go / F#.

## Context

`gsc` version: `Gsharp.NET.Sdk/0.1.459`, .NET 10 RTM.

Discovered while porting `tests/Oahu.Cli.Tests/Server/McpServerTests.cs` and `HttpServerIntegrationTests.cs` to G#. Both tests need to construct `ServerHost.ServiceFactories` (a `public sealed class` nested in a `public static class ServerHost`) and configure its delegate-typed init-only properties before passing it to `ServerHost.BuildStdioHost`. The static-method dispatch (`ServerHost.BuildStdioHost(...)`) works fine on its own; only the nested-type construction blocks the port.

(Bonus note: the same `Microsoft.AspNetCore.*` reference-flow issue also blocks HttpServerIntegrationTests — `<FrameworkReference Include="Microsoft.AspNetCore.App" />` doesn't seem to flow transitively through a `<ProjectReference>` in a `Gsharp.NET.Sdk` consumer. May or may not be a separate issue — not filed here.)

**Comment by DavidObando** [comment]
✅ Fixed in `Gsharp.NET.Sdk/0.1.509`. Verified end-to-end in the Oahu G# experiment.

Closing.
