### ISSUE TITLE
migrated test/Compiler.Tests: 20 errors revealed once src/Repl compiles (12× GS0159, 4× GS0158, 3× GS0155, 1× GS0113)

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#3745]
Unmasked by PR #3744 (issue #3739). `test/Compiler.Tests` project-references `src/Repl`, which failed to compile on a single `GS0227`. A dependency that never produces an assembly stops the consumer before it binds anything of its own, so Compiler.Tests reported exactly one error — its dependency's. With Repl fixed it now reports **20 errors of its own**:

```
GS0159 ×12   Cannot find function …
GS0158 ×4    Cannot find member …
GS0155 ×3    Cannot convert type …
GS0113 ×1
```

These are pre-existing translator/binder gaps, **not** regressions from #3744 — they were simply unreachable while the dependency was red. Net gate effect of #3744 is therefore +1 app (`src/Repl`), not +2.

## Approach

**Triage first**, as with #3724 (which found 14 errors → 4 root-cause families → 0 regressions). Group by root cause rather than diagnostic id — one failed lookup routinely cascades into several `GS0159`s, so 20 errors is likely far fewer than 20 causes. Post the triage before fixing anything.

Check each against the already-solved families before concluding it is new; a reappearance is a **regression** and should be called out loudly. Solved so far: annotated null flows #3644/PR #3656 · oblivious reads #3635/PR #3650 · oblivious call results #3683/PR #3701 · tuple-element taint #3641/PR #3657 · deconstructed foreach #3663/PR #3665 · qualified generic statics #3658/PR #3661 · nested-type→enclosing-`shared` calls #3660/PR #3662 · lambda/delegate erasure #3659/PR #3664 and #3666/PR #3667 · extension receiver inference #3673/PR #3680 · generated-code declarations #3676/PR #3690 · iterator slot names #3689/PR #3692 · friend-assembly internals #3679/PR #3693, #3684-F7/PR #3702, #3705/PR #3707 · delegate nullable returns #3695/PR #3703 · overloaded method-group erasure #3712/PR #3713 · array covariance #3685/PR #3688 · load context #3705/PR #3716 · `[InlineData(null)]` taint #3726/PR #3735 · imported-homonym lambda parameters #3725/PR #3733 · cross-project `open` #3724-A/PR #3731 · signature-position nullability #3705 family 2/PR #3741.

## Measurement notes

- **Validate with dependencies in the `--app` list.** Never exclude a project the target references — that is exactly what produced this masking, and it also buried `LanguageServer.Tests` under 734 `GS0536` from `src/LanguageServer` (#3724) and hid #3714 behind `Cs2Gs.CodeModel`.
- Exclude `GS0536` "redundant `!!`" from substantive counts (polish artifacts; convergence fixed in #3728).
- The gate compiles through the **packed** `Gsharp.NET.Sdk` nupkg, so `dotnet build GSharp.sln -c Release -graph` before any migration run.
- The migrated `.gsproj` pins the SDK by a `git describe` version that does **not** change on working-tree edits, so a genuine before/after needs a real commit checkout, not a file revert.

## Why it matters

`test/Compiler.Tests` is one of six apps still failing at compile in the selfmig gate (41/51, floor 41). The others: `src/Repl` (fixed by #3744), `test/Core.Tests` (#3684's remaining families), `test/InternalAnalyzers.Tests` (#3686, ADR-0169 M5), `test/Sdk.Tests`, `tools/cs2gs/Cs2Gs.Tests`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by DavidObando** [comment]
## Triage: 20 errors → **6 root-cause families**, **0 regressions**

Measured on `origin/main` @ `cec369958` (gsc `0.4.349+cec369958b`), whole-repo `cs2gs migrate` (50/51 apps translated; the one failure is the known `test/Interpreter.Tests` `translation-unsupported`), then `cs2gs validate` with `test/Compiler.Tests` **and every project it references** in the `--app` list — `src/Core`, `src/Compiler`, `src/LanguageServer`, `src/Repl`, `tools/gsgen/GSharp.GeneratorHost`, `tools/gsgen/Gsgen.Cli`, `test/Compiler.Tests`. Result: **6/7 apps green**; `test/Compiler.Tests` is the only red one, with exactly the 20 errors this issue predicted (12× GS0159, 4× GS0158, 3× GS0155, 1× GS0113). No `GS0536` in the substantive count.

Checked every family against the ~22 already-solved ones listed above. **None is a reappearance — there are no regressions here.** Two are *adjacent* to solved work and are called out as such below.

| # | root cause | errors | layer | status | tractable |
|---|---|---|---|---|---|
| F1 | user class → imported interface lost for **ordinary arguments** | **13** | gsc | new | yes — **fixed** |
| F2 | named tuple element names lost across `await` | 2 | gsc | new (ADR-0172 area) | yes |
| F3 | `nil` rejected as an element of a **nullable** params array | 2 | gsc | new | yes |
| F4 | named tuple → `object?` boxing in a **lambda** return | 1 | gsc | new | yes |
| F5 | conversion-call on a **nested** imported enum type | 1 | gsc | new | yes |
| F6 | cs2gs drops the static extension-**holder class** | 1 | cs2gs | new | yes |

20 errors, 6 causes. **3 of the 20 are pure cascades** off F1's failed lookups (see below), so the substantive count is 17 sites across 6 causes.

---

### F1 — user class → imported interface lost for ordinary arguments (13 errors, gsc) — LARGEST, fixed

A user-declared G# class has no CLR `Type` while it is being compiled, so `ExpressionBinder.GetEffectiveArgumentClrTypeForOverloadResolution` erases it to its imported **base** type, or to `System.Object` when it has none. The implemented imported **interfaces** are dropped — and they are the only evidence an imported generic method has for inferring a type parameter that occurs solely inside an interface-typed parameter.

Canonical site — `test/Compiler.Tests/LanguageConformance/NormalizedIlDump.cs:69` (and 8 more in the same file), plus `test/Compiler.Tests/Emit/Issue1208SafeHandlePInvokeEmitTests.cs:69`:

```csharp
private sealed class NameSignatureProvider : ISignatureTypeProvider<string, object> { … }
…
var sig = m.DecodeSignature(provider, genericContext: null);
```

`MethodDefinition.DecodeSignature<TType, TGenericContext>(ISignatureTypeProvider<TType, TGenericContext>, TGenericContext)` — with `provider` erased to `object`, `FindClosedGeneric(object, ISignatureTypeProvider<,>)` finds nothing, `TType` receives no bound, `TryInferTypeArguments` returns false, and the call reports `GS0159 Cannot find function DecodeSignature`.

Roots (10× `GS0159`): `NormalizedIlDump.gs` 52, 69, 121, 256, 262, 276, 283, 320 and 269 (`DecodeSignature` / `DecodeLocalSignature` / `DecodeFieldSignature` / `DecodeMethodSignature`), `Issue1208SafeHandlePInvokeEmitTests.gs:54`.

Cascades (3, no separate cause): `Issue1208SafeHandlePInvokeEmitTests.gs:55` `GS0158 Cannot find member ReturnType` and `:62` `GS0158 … ParameterTypes` — both on `sig`, the error-typed result of the failed decode; `NormalizedIlDump.gs:123` `GS0159 Cannot find function Append` — `builder.Append(string.Join(", ", locals))` where `locals` is the error-typed result of line 121.

*Adjacent, not a regression:* issue #1423 already projects a user class to its most-derived implemented CLR interface — but only for an extension method's **receiver** (`TryProjectUserClassReceiverInterface`, called once, from the extension path). Ordinary arguments never got the projection. Note the static-call form (`Enumerable.Count(bag)`) is a *different* path and already worked; the gap is the instance/ordinary-argument path.

20-line repro (fails on `main`, passes with the fix): a G# class implementing `ISignatureTypeProvider[string, object]` passed to `method.DecodeSignature(provider, nil)`.

**Fixed in this PR** by extending the same projection to ordinary arguments, plus an executing regression test (`Issue3745UserClassInterfaceArgumentInferenceEmitTests`) that decodes a real method signature rather than only binding.

### F2 — named tuple element names lost across `await` (2 errors, gsc)

`test/Compiler.Tests/Emit/Issue3421GenericInterfaceCastEmitTests.cs:88`:

```csharp
private static async Task<(string Output, IReadOnlyDictionary<string, byte[]> MethodIl)> CompileInspectAndRun(…)
…
var result = await CompileInspectAndRun(source, "CheckedCast3421", "ImplicitCast3421");
Assert.Equal(…, result.Output);            // GS0158 Cannot find member Output   (Issue3421….gs:58)
… result.MethodIl!["CheckedCast3421"] …    // GS0158 Cannot find member MethodIl (Issue3421….gs:59)
```

`await` of a `Task[(named tuple)]` yields the unnamed shape. Repro:

```gs
async func Produce() Task[(Output string, Count int32)] { return (Output: "a", Count: 1) }
async func Consume() Task { let t = await Produce(); Console.WriteLine(t.Output) }   // GS0158
```

ADR-0172 territory (`MemberLookup.ResolveCallReturnTypeFromSymbolicTypeArgs` already special-cases `Task`1` for symbolic projection; the named-element carry does not survive the await unwrap). Not one of the solved families.

### F3 — `nil` rejected as an element of a nullable params array (2 errors, gsc)

`test/Compiler.Tests/Emit/Issue2398ExpressionTreeLiftedUserOperatorEmitTests.cs` → migrated lines 52 and 91:

```gs
Assert.False(bool(compiled.DynamicInvoke(present, nil)!!))
Assert.Null(compiled.DynamicInvoke(present, nil))
```

→ `GS0155 Cannot convert type 'nil' to 'object'` — note the target prints as `object`, not `object?`. `Delegate.DynamicInvoke(params object?[]? args)` has a **nullable params array**; the element's nullability is lost when the array type is unwrapped. `string.Format("{0} {1}", "x", nil)` (params `object?[]`, array not nullable) binds fine, which isolates it to the nullable-array form. Repro: `del.DynamicInvoke("x", nil)` on a `Delegate`.

*Adjacent, not a regression:* signature-position nullability (#3705 family 2 / PR #3741) was about signature positions; this is params-array element nullability. Distinct.

### F4 — named tuple → `object?` boxing in a lambda return (1 error, gsc)

`test/Compiler.Tests/IlVerifierTests.cs:206` → migrated `IlVerifierTests.gs:146`:

```gs
let exception = Assert.Throws[XunitException](func () object? {
    return IlVerifier.RunProcess(…)      // GS0155: '(ExitCode int32, Stdout string?, Stderr string?)' → 'object?'
})
```

Narrow: an **unnamed** tuple returned from the same lambda converts fine, and a **named** tuple returned from a plain `func` converts fine. It is only named-tuple + lambda-return that the conversion classifier rejects.

### F5 — conversion-call on a nested imported enum type (1 error, gsc)

`test/Compiler.Tests/Issue2920ReleaseJitOptimizerTests.cs:78`: `(DebuggableAttribute.DebuggingModes)expectedFlags` translates to the G# conversion-call form `DebuggableAttribute.DebuggingModes(expectedFlags)`, and gsc reports `GS0159 Cannot find function DebuggingModes` — it does not resolve a **nested** imported type in conversion-call position. One-liner repro: `let flags = DebuggableAttribute.DebuggingModes(2)`.

*Adjacent, not a regression:* the solved nested-type family (#3660 / PR #3662) was nested-type → enclosing-`shared` **calls**; this is the conversion-call direction.

### F6 — cs2gs drops the static extension-holder class (1 error, cs2gs)

`test/Compiler.Tests/Emit/ClrInteropEmitTests.cs:326` declares `public static class NamedParamsExtensionFixture` holding one `this`-extension. cs2gs correctly lowers it to a top-level G# receiver-clause func:

```gs
func (source string) Describe(statusCode int32, responseType Type? = nil, contentType string? = nil, contentTypes ...string) string { … }
```

…and the holder class disappears — but line 246's `typeof(NamedParamsExtensionFixture).Assembly.Location` still names it, so the migrated `ClrInteropEmitTests.gs:192` reports `GS0113 Type 'NamedParamsExtensionFixture' doesn't exist.` The only cs2gs-layer defect in the set: a reference to the elided holder type is left dangling.

---

### Plan

F1 (13/20, 65%) is fixed in the PR that references this issue. F2–F6 get focused issues with the file/line evidence and repros above.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Nng28yiBdPVdeML7mSZphs
