### PR TITLE
gsgen: resolve SDK-bundled analyzers; gsc: base.field access (#4331)

### PR DESCRIPTION
**Pull request by DavidObando**
## Summary

Two independent, verified fixes that surfaced while investigating whether gsgen (ADR-0145) can run the *real* `System.Text.RegularExpressions.Generator` in place of gsc special-casing `[GeneratedRegex]` (ADR-0143 §B). **This PR does not touch that migration itself** — it only fixes two gaps found along the way. It is independent of, and does not touch, the separate open PRs #4326/#4327 (ADR-0187's native `[GeneratedRegex]` path in gsc) — those are left exactly as they are.

### 1. `_GsharpResolveAnalyzers` couldn't see SDK-bundled generators

It only re-invoked `ResolvePackageAssets` (NuGet-lockfile-driven) with `ProjectLanguage=C#` — enough for a NuGet-delivered generator (CommunityToolkit.Mvvm) but not an SDK-bundled one (`System.Text.RegularExpressions.Generator`, `System.Text.Json.SourceGeneration`, the `Microsoft.Interop.*` generators), which ship in the `Microsoft.NETCore.App.Ref` targeting pack and are resolved by the separate `ResolveTargetingPackAssets` task.

Confirmed empirically: a throwaway net10.0 `.gsproj` with **no** `PackageReference` resolved `@(GsharpAnalyzer)` to nothing before this fix, and to 6 targeting-pack generators after re-invoking `ResolveTargetingPackAssets` a second time with `ProjectLanguage=C#` (mirroring the existing `ResolvePackageAssets` re-invocation).

`Microsoft.Interop.LibraryImportGenerator` is explicitly excluded from the result: gsc already implements `@LibraryImport` natively end-to-end (ADR-0092's `PInvokeBinder`), so letting the real generator also fire on the same trigger would be a second, uncoordinated implementation of the same member. `ComInterfaceGenerator`/`JSImportGenerator`/`SourceGeneration` have no gsc-native equivalent (checked — no binder references either attribute) and are left resolvable.

Verified no regression: `e2etests/gsgen-e2e.sh` (the existing CommunityToolkit.Mvvm NuGet-generator integration test) still passes at its strongest level, and `test/Sdk.Tests` (93 tests) is green.

### 2. `base.fieldName` (read) and `base.fieldName = value` (write) had no G# spelling

Issue #986 gave `base.M(...)` a non-virtual spelling for inherited **methods**, and #1104 extended the plain/bracketed forms to inherited **properties** — neither covered a plain **field**. Surfaced by the real `[GeneratedRegex]` generator's own emitted matcher, which reads/writes inherited `RegexRunner` protected fields via `base.`. Filed as #4331.

Fields are never virtually dispatched, so this needed no new emission shape: it reuses the exact `BoundFieldAccessExpression` (GSharp-native base) / `BoundClrPropertyAccessExpression` (imported CLR base) that an ordinary `this.field`/`obj.field` read or write already produces — rooted at the resolved *base* type (so a field the derived class shadows still reaches the base's own storage) instead of the most-derived receiver type.

Covers both:
- an imported CLR base's protected field (`System.Text.RegularExpressions.Regex.pattern`)
- a GSharp-native `open class` base's own field

New tests: `test/Core.Tests/CodeAnalysis/Binding/Issue4331BaseFieldAccessBinderTests.cs` (3 tests, end-to-end compile+run via `EmittedOracle`). Regression check: all 324 "Base"-named `Core.Tests` and 304 "Base"-named `Compiler.Tests` pass.

### A third "gap" that turned out not to exist

The original investigation also suspected a missing `ReadOnlySpan<T>.Slice(int)` single-argument overload (`GS0159 Cannot find function Slice`). This does **not** exist as an independent gsc gap — it was a downstream cascade of gap 2: once `pos = base.runtextpos` failed to bind, `pos`'s type went to `Error`, and `Slice(pos)` failed to resolve *any* overload for that reason, not because the overload is missing. Verified directly: `Slice(int)` already worked in isolation before this fix (existing test fixtures already exercise it), and after fixing `base.field`, the combination `base.runtextpos` + `Slice(pos)` binds cleanly with zero changes to Slice resolution. No fix needed; not included here.

## Scope note

This PR is deliberately scoped to the two language/SDK fixes above. The larger question this investigation was chasing — actually migrating `[GeneratedRegex]` from gsc's native handling (or cs2gs's `__generatedRegex_` synthesis, tracked in #4301) to gsgen running the real generator — is blocked on a bigger, previously-unknown gap: **G# has no partial-method (function-level `partial`) declaration syntax at all**, only partial classes/structs/interfaces. Confirmed by hand: `partial func Bar() int32` does not parse (cascading syntax errors, `partial` isn't recognized as a member modifier). The MVVM/CommunityToolkit case gsgen already supports works because that generator *adds new members* to a partial class; `[GeneratedRegex]`'s C# shape requires merging two halves of the *same partial method* (a declaration part + a generator-supplied implementation part), which has no G# grammar to express yet. That is a substantial new language feature, not a quick follow-up, so it is **not** attempted here — reported back separately rather than forcing a half-working PR. #4301 is left untouched (open, no comment) since nothing in this PR addresses it.

## Test plan
- [x] `test/Sdk.Tests` — 93/93 passed
- [x] `test/Core.Tests` filtered to `Base` — 324/324 passed
- [x] `test/Compiler.Tests` filtered to `Base` — 304/304 passed
- [x] `e2etests/gsgen-e2e.sh` — PASS(STRONG), no regression on the MVVM NuGet-generator path
- [x] Manual empirical probes (throwaway `.gsproj`, real `RegexRunner`/`Regex` BCL types) for both fixes, compiled and run

### CODE REVIEW

File: src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Arguments.cs [hunk 1]
```diff
@@ -3444,6 +3444,25 @@ private BoundExpression BindBaseClassPropertyRead(
...
+            // Issue #4331 (base-field-access): the nearest GSharp base declares
+            // a plain FIELD (not a property) of this name. Fields are never
+            // virtually dispatched, so this needs no non-virtual distinction —
+            // it produces the exact same BoundFieldAccessExpression an ordinary
+            // `this.Field`/`obj.Field` read would, just rooted at the resolved
+            // base type rather than the most-derived one, so a field the
+            // derived class shadows still reads the base's own storage.
+            if (searchBase != null
+                && TypeMemberModel.TryGetFieldIncludingInherited(searchBase, memberName, MemberQuery.Instance(MemberKinds.Field), out var baseField, out var baseFieldDeclaringType)
+                && GetEffectiveThisParameter() is { } fieldReadThisParameter)
```
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Core/CodeAnalysis/Binding/ExpressionBinder.Calls.Arguments.cs]: Confirmed and fixed. Traced `TryGetProperty` (`TypeMemberModel.cs`) — it walks `searchBase`'s entire ancestor chain checking only `.Properties` before ever returning false, so a same-named property on a distant ancestor was winning over a field the immediate base declares. Moved the field check (both read and write) to run first and unconditionally, matching the field-before-property precedence the ordinary `this.field`/`obj.field` lookup already follows in `ExpressionBinder.Access.MemberLookup.cs:495-525`.

Added `BaseField_NearerFieldBeatsFartherProperty_ReadAndWrite` with exactly the shape you described (grandparent declares a property, immediate parent declares a same-named field), and independently probed the grandparent's property via the ADR-0091/#1104 explicit base-selector form (`base[Grandparent].X`) to prove `base.X` never touches it. Verified the test fails on the pre-fix ordering (grandparent property incorrectly won: output `"42\n42\n"`) and passes after the fix (`"42\n111\n"`, grandparent property untouched). Full base-related regression suite (325 Core.Tests) still green.

Pushed in 412725a1.

File: src/Sdk/Gsharp.NET.Sdk/build/Gsharp.NET.Core.Sdk.targets [hunk 2]
```diff
@@ -298,6 +322,60 @@
...
+         independent implementation of the same member with no coordination
+         between the two — remove it here rather than risk that collision.
+         Microsoft.Interop.ComInterfaceGenerator (`[GeneratedComInterface]`)
+         and Microsoft.Interop.JavaScript.JSImportGenerator have no gsc-native
+         equivalent (confirmed empirically — no binder references either
+         attribute) and Microsoft.Interop.SourceGeneration is shared interop
+         infrastructure those two depend on, so all three are left resolvable. -->
+    <ItemGroup>
+      <_GsharpNativelyImplementedAnalyzer Include="@(GsharpAnalyzer)" Condition="'%(GsharpAnalyzer.AssemblyName)' == 'Microsoft.Interop.LibraryImportGenerator'" />
+      <GsharpAnalyzer Remove="@(_GsharpNativelyImplementedAnalyzer)" />
```
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Sdk/Gsharp.NET.Sdk/build/Gsharp.NET.Core.Sdk.targets]: Verified both claims against the actual target/task ordering before fixing:

- The bypass claim is confirmed exactly as described: `@(Analyzer)` (user-supplied) was unioned in AFTER the LibraryImportGenerator exclusion filter ran, so a user `<Analyzer Include=".../LibraryImportGenerator.dll">` bypassed it. Verified empirically both ways with a throwaway .gsproj: bypassed (5 → 6 resolved analyzers, LibraryImportGenerator present) before this fix, excluded (back to 5) after.
- The ordering claim for `ResolveOffByDefaultAnalyzers` is also true as stated — but I traced through to the actual consequence and it's more nuanced than 'stays enabled': that target's `Remove` only ever touches `@(Analyzer)` (the STANDARD, default-language invocation's output), never `@(GsharpAnalyzer)` (where our SECOND, C#-language invocation's `AnalyzersToAdd` lands), regardless of execution order — so it was never actually filtering our item list at all, by construction, not by timing. Added the identical off-by-default removal directly to `@(GsharpAnalyzer)`, gated the same way (`EnableRequestDelegateGenerator`/`EnableConfigurationBindingGenerator`).

  One honesty note I want on the record rather than silently fixed: empirically, on the SDK version I verified against (10.0.401 / ref pack 10.0.12), `ResolveTargetingPackAssets`'s own `AnalyzersToAdd` output already excludes RequestDelegateGenerator/ConfigurationBindingGenerator regardless of whether this new filter is present — for a reason I did not fully root-cause (possibly a Roslyn/analyzer-API-version check inside the task itself, unrelated to `ResolveOffByDefaultAnalyzers`). So I could not empirically prove this specific sub-fix changes observable behavior on this SDK version. I kept it anyway — it's correct, documented, defense-in-depth parity with the standard SDK's own mechanism, and would matter on an SDK version where that upstream exclusion doesn't hold. Flagging so it isn't mistaken for a verified-necessary fix.

Restructured to union ALL sources (NuGet + targeting-pack + user `@(Analyzer)`) first, then apply both filters once over the full set, keyed on the well-known/intrinsic `%(FileName)` metadata (confirmed populated for a plain user `<Analyzer Include="..."/>` item too, unlike `AssemblyName` which only resolved-task output items carry) — matching `ResolveOffByDefaultAnalyzers`'s own match key.

Pushed in 412725a1.

File: src/Sdk/Gsharp.NET.Sdk/build/Gsharp.NET.Core.Sdk.targets [hunk 3]
```diff
@@ -298,6 +322,60 @@
...
+         ProjectLanguage=C#, reusing the @(FrameworkReference)/
+         @(ResolvedTargetingPack) items the standard target already resolved.
+         ReferencesToAdd and the task's other outputs are deliberately left
+         unwired here: the first (default-language) invocation already folded
+         the targeting pack's reference assemblies into @(Reference); wiring
+         ReferencesToAdd again would duplicate that item group. -->
+    <ResolveTargetingPackAssets
+        FrameworkReferences="@(FrameworkReference)"
+        ProjectLanguage="C#"
+        ResolvedTargetingPacks="@(ResolvedTargetingPack)"
```
[the remark this answers is not in the document]
Comment (DavidObando) [reply src/Sdk/Gsharp.NET.Sdk/build/Gsharp.NET.Core.Sdk.targets:346]: Verified: `Sdk.Tests` has no MSBuild-evaluation harness at all (no `Microsoft.Build`/`Microsoft.Build.Locator` reference, only `Microsoft.Build.Framework`/`Utilities.Core` for task-level unit tests) — the existing gsgen integration coverage lives entirely in `e2etests/gsgen-e2e.sh`, which builds a real packed-SDK project via `dotnet build` and inspects the output, not in xunit. That script only ever exercises the NuGet/CommunityToolkit.Mvvm path, so you're right that the new targeting-pack path (and the filtering added in the other finding) had zero automated coverage.

Rather than force a full MSBuild-evaluation harness into `Sdk.Tests` (inconsistent with how this exact kind of SDK-wiring integration is already tested here), added a 'Phase 0' scenario to `e2etests/gsgen-e2e.sh` mirroring the existing script's own pattern: a throwaway project with NO `PackageReference` (plus a `Microsoft.AspNetCore.App` `FrameworkReference` to also exercise the off-by-default path), asserting `@(GsharpAnalyzer)` resolves `System.Text.RegularExpressions.Generator` while excluding `LibraryImportGenerator` and `RequestDelegateGenerator`. Verified it fails without the other finding's fix (LibraryImportGenerator bypass reproduces) and passes with both fixes applied; both phases of the script pass end to end.

Pushed in 412725a1.
