### ISSUE TITLE
gsc: chained .Select(...).Select(...) over a generic-interface element type fails on the 2nd Select (GS0159)

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#1422]
Found migrating Oahu.Decrypt (InterleavedIterator) via cs2gs. Refs #914.

A second `.Select(...)` whose source element type is a generic interface (`IEnumerator[T]`) cannot resolve, even though each `Select` compiles in isolation.

Repro (`gsc /target:library`, BCL refs):
```
import System
import System.Collections.Generic
import System.Linq

func C[T](xs []IEnumerable[T]) []int32 ->
    xs.Select((e IEnumerable[T]) -> e.GetEnumerator())
      .Select((e IEnumerator[T]) -> 1)
      .ToArray()
```
=> `GS0159: Cannot find function Select` on the second call.

Root: the inferred element type of the first projection (`IEnumerator[T]`) isn't matched against the `Select` extension's `IEnumerable[TSource]` self-parameter, so the second Select's overload set is empty.
