### ISSUE TITLE
gsc: a `map[K, Derived]` does not reach an inferred `Dictionary<K, V>` slot the `List` spelling reaches

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#4016]
Found while writing tests for #4006. Pre-existing on `main` (`b6d2f60e`), and NOT introduced by the #4006/#4000 PR — measured identical on both sides of it.

## Repro (measured on `main`)

C# library (`<Nullable>enable</Nullable>`):

```csharp
using System.Collections.Generic;

namespace HelperLib;

public class ImportedBase { }

public static class Probes
{
    public static string CountAny<T>(List<T> items) => "any:" + items.Count;

    public static string CountAnyMap<K, V>(Dictionary<K, V> entries)
        where K : notnull
        => "anymap:" + entries.Count;
}
```

```gs
package P
import System
import System.Collections.Generic
import HelperLib

class Derived : ImportedBase {
}

// binds, verifies, runs — prints `any:1`
let items = List[Derived]()
items.Add(Derived{})
Console.WriteLine(Probes.CountAny[Derived](items))

// GS0159
let entries = map[string, Derived]{}
entries["k"] = Derived{}
Console.WriteLine(Probes.CountAnyMap[string, Derived](entries))
```

```
error GS0159: Cannot find function CountAnyMap.
    Console.WriteLine(Probes.CountAnyMap[string, Derived](entries))
```

## Why this is the asymmetry

Both calls are the same shape: a same-compilation class element, at an **inferred generic slot**, with the type arguments given EXPLICITLY. An inferred slot is exactly what the ADR-0004 erasure exists to serve — a `List[Derived]` reaches `CountAny[T](List<T>)` because the slot's `object` came from erasure, which is what `ClrOverloadResolution.IsErasedGenericParameterSlot` is for.

The `map` spelling does not get there. `map[string, Derived]` presents as `Dictionary<string, ImportedBase>` (the imported-base surrogate from `MemberLookup.TryProjectErasedClrType`), not as `Dictionary<string, object>`, so it never looks like an erased slot's shape and the candidate is not applicable.

That surrogate difference between the `List` spelling and the `map` spelling is the same one #4006 turns on; there it made a call bind that should not, here it makes a call fail that should bind. This one is not a soundness problem — nothing wrong is emitted — but it is a completeness gap in the same place, and it means the two spellings of "a collection of a same-compilation class" behave differently at an imported generic method.

## Controls

- `map[string, int32]` at `CountAnyMap[string, int32]` — binds.
- `List[Derived]` at `CountAny[Derived]` — binds (the row above).
- Explicit vs inferred type arguments makes no difference.

## Expected

`map[string, Derived]` reaches `CountAnyMap[K, V](Dictionary<K, V>)`, closed over the real `Derived`, exactly as `List[Derived]` reaches `CountAny[T](List<T>)`.

## Notes

- Not channel business, so no ADR-0174 erratum.
- The #4006 PR's fixture carries the `List` spelling as a green row and names this issue where the `map` row would otherwise sit.

**Comment by DavidObando** [comment]
The PR that occasioned this finding is #4019 (fixes #4006 and #4000). Its #4006 fixture carries the `List` spelling as a green row and names this issue where the `map` row would otherwise sit.

**Comment by DavidObando** [comment]
## Correction: the boundary in this issue is wrong in three ways (measured on `main` @ `a09f4e1b`)

Working this now. A 20-case matrix run against `main` contradicts the Controls section and the title. The **failure is real and the "Why" is half right**, but it needs three things at once, not one:

**structural spelling + EXPLICIT type arguments + a type argument that is a same-compilation class WITH an imported base.**

| row | spelling | type args | element | result on `main` |
|---|---|---|---|---|
| `Probes.CountAnyMap[string, Derived](map[string, Derived]{})` | `map` | explicit | `Derived : ImportedBase` | **GS0159** |
| `Probes.CountAnyMap(map[string, Derived]{})` | `map` | **inferred** | `Derived : ImportedBase` | **binds** |
| `Probes.CountAnyMap[Derived, string](map[Derived, string]{})` | `map` | explicit | key position | **GS0159** |
| `Probes.CountAnyMap[string, Standalone](map[string, Standalone]{})` | `map` | explicit | `Standalone` (no base) | **binds** |
| `Probes.CountArray[Derived]([]Derived{…})` | **slice** | explicit | `Derived : ImportedBase` | **GS0159** |
| `Probes.CountArray[Derived]([2]Derived{…})` | **array** | explicit | `Derived : ImportedBase` | **GS0159** |
| `Probes.CountArray(…)` (same, inferred) | slice | inferred | `Derived : ImportedBase` | **binds** |
| `Probes.CountAny[Derived](List[Derived]())` | `List` | explicit | `Derived : ImportedBase` | binds |

1. **"Explicit vs inferred type arguments makes no difference" is wrong** — it is the whole difference. Inferred *always* bound, because inference reads the argument's own shape instead of a placeholder.
2. **"a same-compilation class" is too broad** — a same-compilation class with *no* imported base always bound. Only one with an imported base failed.
3. **The title is too narrow: this is not `map`-versus-`List`.** `[]Derived` and `[N]Derived` at a `T[]` slot fail identically, for the identical reason.

### Mechanism — the argument side is right, the lever is not

The issue is correct that `map[string, Derived]` presents as `Dictionary<string, ImportedBase>`. Traced at the applicability loop:

```
PRE arg[0] param=Dictionary`2[System.String,System.Object]
           arg=Dictionary`2[System.String,HelperLib.ImportedBase] conv0=None structProj=False
CAND System.String CountAnyMap[String,Object](Dictionary`2[System.String,System.Object]) ok=False
```

The parameter is closed over **`System.Object`**, not over the surrogate. `ExpressionBinder.Calls.Invocation.TryResolveExplicitMethodTypeArgs` closes a type argument with no reference-context CLR type over a flat `System.Object` placeholder (issue #320), while `MemberLookup.TryProjectErasedClrType` — the projection every structural *argument* goes through — erases a same-compilation class to its imported base (`StructSymbol { IsClass: true }` → `ImportedBaseType?.ClrType ?? typeof(object)`). Two projections of one class that disagree; `Dictionary<,>` and `T[]` are invariant, so nothing converts.

`List[Derived]` was green only by accident: it takes the `ImportedTypeSymbol` branch into `TryBuildErasedClosedGeneric`, whose component eraser (`ProjectSymbolicArgToErasedClr`) has **no user-class arm** and answers `object` — which is exactly what the flat placeholder produced, so those two already agreed.

So `TryProjectErasedClrType` is not the thing to change (it is what #4006 turns on). The fix is at the placeholder: project the explicit type argument the same way the arguments are projected. That is the correction #3087 already made one site over for symbolic tuple type arguments.

### Separate pre-existing hole found while measuring — filed as its own issue, not fixed here

Naming a **base** of the real element as the explicit type argument compiles and runs but emits IL ILVerify rejects, on `main` and unchanged by the fix:

```gsharp
Probes.CountAny[ImportedBase](List[Derived]())   // and the map spelling
```
```
[IL]: Error [StackUnexpected]: [offset 0x0000000F]
[found ref 'List`1<P.Derived>'][expected ref 'List`1<HelperLib.ImportedBase>'] Unexpected type on the stack.
```

It is admitted as an ADR-0148 `StructuralProjection` at an erased slot (`conv=StructuralProjection erasedSlot=True`) and nothing is emitted for the projection. A #4006-shaped hole in the explicit-type-argument path; out of scope for the fix here.
