### ISSUE TITLE
gsi: Optional.FlatMap with a nullable-returning lambda throws TargetInvocationException

### ISSUE THREAD

**Issue by DavidObando** [DavidObando/gsharp#2995]
## Problem

`Optional.FlatMap` with a lambda returning a nullable throws in the interpreter.

`samples/GsharpExtensionsOptional.gs`:

```gsharp
let upper = name.Map(func(s string) string { return s.ToUpper() })   // works, prints ADA
let firstChar = upper.FlatMap(func(s string) string? {               // throws
    if s.Length > 0 { return s.Substring(0, 1) }
    return nil
})
```

```
compiled: ADA A default computed <filtered out> present: ada ada 14 -1 7 count present: 7
gsi:      ADA
          GS9999: Exception has been thrown by the target of an invocation.
```

`Map` succeeds and `FlatMap` fails, so the extension-method dispatch itself works — it is specifically the nullable-returning lambda.

## Notes

The message is a bare `TargetInvocationException` with the inner exception discarded, which is itself unhelpful — surfacing `InnerException` would make this and similar failures diagnosable. That is closely related to #2938 (interpreter loses uncaught delegate exception diagnostics through CLR member calls) and may share a fix.

Found while triaging #2939; excluded there until fixed. The sibling samples `GsharpExtensionsMixed.gs` and `GsharpExtensionsSequences.gs` both pass, so this is not a general extensions-resolution problem.

**Comment by DavidObando** [comment]
## Triage: this is two defects, and neither one is `FlatMap`, nullables, or extension dispatch

Measured with a direct `Compilation.Evaluate` probe (the same entry point `gsi` drives) against builds of `8dddbbf2` (base) and `f816c794` (PR #2972 head), Core DLL identity md5-verified in each probe output directory.

### 1. The diagnostic half **is** #2938, and PR #2972 fixes it — measured, not inferred

Reduced repro with **no** `Gsharp.Extensions` dependency, same shape (lambda passed across a CLR reflection boundary):

```gsharp
import System
import System.Linq

let xs = []string{"ada", "bob"}
let ys = xs.Select(func(s string) string? {
    if s.Length > 0 {
        return s.Substring(0, 1)
    }
    return nil
})
Console.WriteLine(ys.Count())
```

| build | output |
|---|---|
| base `8dddbbf2` | `GS9999: Exception has been thrown by the target of an invocation.` |
| head `f816c794` (#2972) | `GS9999: Unexpected node IfStatement` |

That is a base-vs-head behavioural flip on the exact string this issue reports. `Compilation.cs:333` is the sole GS9999 construction site in the interpreter, and at current `main` (`a6b1561f2`) it is still `var message = ex.Message;` — verified by `git show`. PR #2972 changes it to unwrap.

**So the "bare `TargetInvocationException` with the inner exception discarded" complaint in the Notes section is a duplicate of #2938 and needs no separate work.**

### 2. The real defect underneath: lambda bodies are never lowered

Once #2972 removes the mask, the true exception is `Unexpected node IfStatement`, thrown at:

- **`src/Core/CodeAnalysis/Evaluator.Statements.cs:198`** — the `default:` arm of the flat statement-list loop.

That loop consumes a **lowered** block (conditional-goto + label form). `BoundNodeKind.IfStatement` reaching it means the body arrived **unlowered**.

Two discriminating probes settle what is actually broken:

| probe | result |
|---|---|
| lambda body **with `if`**, invoked **directly** in G# (no CLR boundary) | **fails**: `Unexpected node IfStatement` |
| lambda body **without `if`** (single `return`), passed through CLR `Select` | **works**, prints `2` |

So it is **not** the CLR delegate boundary and **not** the nullable return type. It is: **any block-bodied lambda whose body contains a statement requiring lowering fails in the interpreter.** `FlatMap` was incidental — the sample's `FlatMap` lambda is simply the first one in that file with an `if` in it, and `Map`'s lambda is a single `return`, which is why `Map` printed `ADA` and `FlatMap` did not.

This is considerably broader than the issue title suggests and should be retitled.

### Root cause location

Every other function body is lowered at bind time — `Binder.cs:1382`, `:1441`, `:1606`, `:1785`, `:1965` all call `Lowerer.Lower`. The block-bodied lambda/local-function path does not:

- **`src/Core/CodeAnalysis/Binding/LambdaBinder.cs:370`** (at `a6b1561f2`; `:364` at `f816c794`) — `body = bindBlockStatement(syntax.Body);` with no `Lowerer.Lower`.

Corroboration that this is an omission rather than a design choice: `LambdaBinder.cs:1307` *does* call `Lowerer.Lower(body)` but **discards the result** — it is only feeding `ControlFlowGraph.AllPathsReturn`. `LambdaBinder.cs:1715` lowers only the synthetic `never`-block special case. The lowered form is computed and thrown away; the stored body stays unlowered.

The compiled path works, so the emitter either lowers separately or tolerates the unlowered tree. **A fix agent must not assume lowering at bind time is safe** — changing what the emitter receives is the risk in this fix, and it is why the alternative (lower on demand inside the interpreter when it encounters an unlowered lambda body) may be the smaller and safer change. Decide that with a probe, not by reasoning.

### Cluster check — this is **not** in the delegate-conversion cluster

Explicitly, since it was asked: the root cause is in the **binder's lambda body path** (`LambdaBinder.cs`) surfacing at the **statement dispatch loop** (`Evaluator.Statements.cs:198`). It does not land in the delegate conversion or delegate identity code that #2985, #2989, #2990 and #2991 are converging on (`Evaluator.Expressions.cs` `InvokeDelegate` / conversion paths). **No file contention** with those, and this should not be collapsed into that PR.

### Reproducibility note worth recording

The `gsi` CLI **cannot** run any `Gsharp.Extensions` sample: `src/Repl/Program.cs` and `src/Repl/Engine/SessionEngine.cs` pass **no** references, `Repl.csproj` has no `Gsharp.Extensions` reference, and `gsi.deps.json` contains zero `Gsharp.Extensions` entries. Placing `Gsharp.Extensions.dll` beside the source, beside `gsi.dll`, or in the working directory all still yield 19 × `GS0159 Cannot find function ...`; the SDK-packaged `gsi` 0.3.1 behaves identically. Whatever produced the `gsi: ADA` line in this issue was not the plain `gsi` CLI. This matters for #2939: any harness that shells out to `gsi` will fail every extensions sample for environmental reasons that are **not** interpreter defects.

### Files a fix would touch

- `src/Core/CodeAnalysis/Binding/LambdaBinder.cs` — lower the block-lambda body at `:370`; **or**
- `src/Core/CodeAnalysis/Evaluator.Statements.cs` — lower on demand before entering the flat loop (the smaller-blast-radius option, since it cannot perturb the emitter).
- `test/Interpreter.Tests/` — new `Issue2995LambdaBodyLoweringTests.cs` covering `if`, `for`, `while`, and `switch` inside a block-bodied lambda, invoked both directly and across a CLR boundary.
- No change needed for the diagnostic half — that is PR #2972.

### Sequencing

This issue should be **reduced to the lowering defect** and the diagnostic half closed as a duplicate of #2938 once #2972 merges. The lowering fix is independent of #2972 and can proceed in parallel; the two touch disjoint code.

**Comment by DavidObando** [comment]
## Correction to this issue's evidence: the `gsi: ADA` line was not produced by the `gsi` CLI

Flagging this because a fix agent will otherwise treat the two-column block in the description as a reproduction and try to observe a phenomenon that cannot be observed.

**The `gsi` CLI cannot run this sample at all.** It has no channel to receive a reference to `Gsharp.Extensions`:

- `src/Repl/Program.cs` and `src/Repl/Engine/SessionEngine.cs` pass **no** references;
- `src/Repl/Repl.csproj` references only `GsharpCore` and `GsharpLanguageServer`;
- `out/bin/Release/Repl/gsi.deps.json` has **zero** `Gsharp.Extensions` entries, so it is not in the TPA;
- `gsi --help` shows the whole surface — `gsi [file.gs] [--help] [--version]`, no `-r`.

Measured on `samples/GsharpExtensionsOptional.gs`: the DLL beside the source, beside `gsi.dll`, and in the working directory all give **19 × `GS0159 Cannot find function ...`**. The SDK-packaged `gsi` 0.3.1 behaves identically. `Map` never binds, so `ADA` can never print.

It was not the existing conformance harness either — `test/Compiler.Tests/LanguageConformance/SampleConformanceTests.cs` has **no `gsi` path** (`grep` for `gsi`/`Repl`/`Evaluate`/`Interpret` returns nothing). It compiles and runs via `gsc` only.

So the `gsi:` column here came from some other instrument, most likely a direct `Compilation.Evaluate` harness with references wired up — which is exactly how I reproduced the underlying defect in the triage comment above.

**Nothing in the earlier triage changes.** The reduced repro I posted uses `System.Linq` only, needs no extensions assembly, and gave a clean base-vs-head flip. The root cause — block-lambda bodies never lowered, `LambdaBinder.cs:370`, surfacing at `Evaluator.Statements.cs:198` — stands, and it explains the reported symptom precisely: `Map`'s lambda is a single `return` and works, `FlatMap`'s contains an `if` and does not.

The practical consequence is only this: **do not attempt to verify a fix for this issue by running the sample through `gsi`.** It will fail at binding either way. Use a direct `Compilation.Evaluate` probe with `ReferenceResolver`, or the reduced `System.Linq` repro. The `gsi` reference-channel gap is being raised separately on #2939.

**Comment by DavidObando** [comment]
## The discriminator is the `if`, not the nullable — 2×2 completed, nullability exonerated

Filed the underlying defect as **#3003** (`gsi`: an `if` statement inside a lambda body throws `Unexpected node IfStatement`). This issue looks like a symptom of it.

### Why suspect it

`Map` works, `FlatMap` throws. The stated difference is the nullable return. But there is a second difference nobody separated:

```gsharp
let upper     = name.Map(func(s string) string { return s.ToUpper() })   // works    — no if
let firstChar = upper.FlatMap(func(s string) string? {                   // throws   — HAS an if
    if s.Length > 0 {
        return s.Substring(0, 1)
    }
    return nil
})
```

`if` inside a **lambda body** hard-fails in `gsi`. Across a reflective CLR boundary the `EvaluatorException` is wrapped and its inner discarded, producing exactly the string reported here.

### Full 2×2, measured on `a6b1561f2`, BCL only — no `Gsharp.Extensions`

| | **no `if`** | **with `if`** |
|---|---|---|
| **non-nullable return**<br>`Predicate[int32] → bool`, via `Array.FindAll` | `2` ✅ | `GS9999: Exception has been thrown by the target of an invocation.` ❌ |
| **nullable return**<br>`Converter[int32, string] → string?` returning `nil`, via `Array.ConvertAll` | `3` ✅ | `GS9999: Exception has been thrown by the target of an invocation.` ❌ |

**Both rows flip on the `if`. Neither column flips on nullability.** A nullable-returning lambda that actually returns `nil` through a reflective CLR boundary works fine (`q1` → `3`).

Direct invocation of the same `if`-bearing lambda, with no CLR boundary, gives the underlying message uncloaked:

```
GS9999: Unexpected node IfStatement
```

### Root cause (detail in #3003)

`BoundTreeRewriter` deliberately does not descend into `BoundFunctionLiteralExpression.Body` (`NestedFunctionBodyRewriter.cs:16-21`), and `Lowerer` is a plain `BoundTreeRewriter` — so lambda bodies are never lowered. `Evaluator.Expressions.cs:762` evaluates the raw body; `Evaluator.Statements.cs:168` throws on the unlowered `BoundIfStatement`. The sibling path `Evaluator.Expressions.cs:781` reads `program.Functions[…]`, which **is** lowered (`Binder.cs:1383`) — which is why the same `if` in a top-level `func` works.

`for`/`while` in lambdas measured working; the binder emits those goto-shaped already. Only `if` is exposed.

### How to falsify this hypothesis

Remove the `if` from `FlatMap`'s lambda, keep the nullable return:

```gsharp
let firstChar = upper.FlatMap(func(s string) string? {
    return s.Substring(0, 1)
})
```

- **Passes** ⇒ this issue is #3003; close as duplicate.
- **Still throws** ⇒ there is a genuine nullable-specific defect *in addition to* #3003, and it needs its own root cause.

### Two cautions before spending effort here

1. **This issue's evidence may not be reproducible as recorded.** `duck-2931` measured that `gsi` has no channel to load referenced assemblies at all — no reference in `Repl.csproj`, zero entries in `gsi.deps.json`, and the DLL beside the source / beside `gsi.dll` / in cwd all give `GS0159`. I reproduced that independently: `gsi --help` exposes only `[file.gs] [--help] [--version]` — no `/r:`, no `/lib:` — and `gsi samples/GsharpExtensionsOptional.gs` fails with `GS0159: Cannot find function Map` before reaching `FlatMap` at all. So whatever produced the reported `gsi: ADA` line was **not** the `gsi` CLI. Re-derive from scratch rather than trusting the transcript. The BCL-only 2×2 above needs no `Gsharp.Extensions`.
2. **PR #2972 / #2938 changes the message, not the outcome.** Better `UnwrapRuntimeException` would surface `Unexpected node IfStatement` instead of the bare `TargetInvocationException` — genuinely valuable, and it would have made this diagnosable immediately — but the call still fails.

### Scheduling consequence

If this is #3003, then this issue is **not** a `TargetInvocationException`-unwrap defect and the fix does not live in `Evaluator.Statements.cs:49-53`. It lives at `Evaluator.Expressions.cs:762`, which is outside both `Expressions.cs:829-880` and `Expressions.cs:1146…1597`.

**Provenance.** SHA-pinned `git clone --shared` scratch clone; `gsi.dll` / `gsc.dll` invoked directly. Tree carries `a6b1561f2`: `merge-base --is-ancestor` true and `git diff a6b1561f2 HEAD -- Evaluator.Expressions.cs Evaluator.Statements.cs Lowering/` empty. Compiled side correct on every probe above.

**Comment by DavidObando** [comment]
## Correction to my own test list above, and a measured scope for this defect

In the triage comment above I proposed covering `if`, `for`, `while` and `switch` in the test list, on the assumption that every construct requiring lowering would fail. **I did not measure that at the time, and it is wrong.** Measured now, `gsi` from a build of `f816c794`, each construct inside a block-bodied lambda:

| construct in a lambda body | result |
|---|---|
| `if` | **fails** — `GS9999: Unexpected node IfStatement` |
| `for v in []int32{1,2,3}` (for-range) | **fails** — `GS9999: Unexpected node ForRangeStatement` |
| `for t < n { }` (condition form) | **works**, prints `3` |
| `switch` / `case` | **works**, prints `one` |
| the same `if` in a **named** function (control) | **works**, prints `1` |

So the failing set is exactly `IfStatement` and `ForRangeStatement`, not "everything that needs lowering".

### Why that set

The interpreter's flat statement loop implements a fixed list of node kinds (`Evaluator.Statements.cs`, cases between `:100` and `:200`):

`VariableDeclaration, ExpressionStatement, GotoStatement, ConditionalGotoStatement, LabelStatement, ReturnStatement, TryStatement, ThrowStatement, PatternSwitchStatement, GoStatement, ChannelSendStatement, SelectStatement, ScopeStatement, FixedStatement, AwaitForRangeStatement, YieldStatement`

`IfStatement` and `ForRangeStatement` are absent because lowering normally eliminates them into `ConditionalGotoStatement`/`LabelStatement` form. Lambda bodies skip lowering, so precisely those two leak through to the `default:` arm at `:198`. `switch` survives because `PatternSwitchStatement` is handled natively, and the condition form of `for` survives because the binder emits kinds already on the list.

That also means the failing set is **not** a stable property to test against — it is whatever the intersection of "binder emits it" and "loop does not handle it" happens to be. The test should assert that `if` and for-range **work**, not enumerate what currently breaks.

### Is this one fix with #2976?

No, and this is measured rather than reasoned. The repro I used for #2976 is a function-literal iterator whose body is `yield 1` / `yield 2` — **no `if`, no for-range, nothing that needs lowering at all**. It still fails, with a different error (`'yield' encountered outside of an iterator function`), because `InvokeClosure` (`Evaluator.Expressions.cs:902`) never pushes an iterator sink. Lowering does not push sinks and `yield` survives lowering as `YieldStatement`, which is on the handled list above.

So a lowered lambda body containing `yield` would still throw. The two defects share a *theme* — lambda bodies skip stages that named functions receive — but they skip **two different stages** (lowering; iterator dispatch) and neither fix closes the other. They should stay separate PRs.

**Comment by DavidObando** [comment]
Measured directly at the #3012 fix head with `out/bin/Release/Repl/gsi samples/GsharpExtensionsOptional.gs`. The `gsi` exit code was captured immediately after execution, before counting or printing output.

Compiled expected output:

```text
1: ADA A default computed <filtered out> present: ada ada 14 -1 7 count present: 7
```

`gsi` output (19 lines examined):

```text
 1: GS0159: Cannot find function Map.
 2: GS0159: Cannot find function WriteLine.
 3: GS0159: Cannot find function FlatMap.
 4: GS0159: Cannot find function WriteLine.
 5: GS0159: Cannot find function OrElse.
 6: GS0159: Cannot find function WriteLine.
 7: GS0159: Cannot find function OrCompute.
 8: GS0159: Cannot find function WriteLine.
 9: GS0159: Cannot find function Filter.
10: GS0159: Cannot find function WriteLine.
11: GS0159: Cannot find function IfPresent.
12: GS0159: Cannot find function IfPresent.
13: GS0159: Cannot find function OrThrow.
14: GS0159: Cannot find function WriteLine.
15: GS0159: Cannot find function Map.
16: GS0159: Cannot find function WriteLine.
17: GS0159: Cannot find function Filter.
18: GS0159: Cannot find function WriteLine.
19: GS0159: Cannot find function IfPresent.
```

`gsi` exit: `1`. The sample never reaches the lambda-lowering defect because the CLI cannot resolve `Gsharp.Extensions`. The isolated in-process `FlatMap` regression passes after #3012, but the issue-scope sample remains unverified. I removed `Fixes #2995` from #3012 and reopened this issue.
